### ISSUE TITLE
python_artifact property redeclared

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#1098]
`HasArtifact` model has two attributes with same name:

https://github.com/thoth-station/storages/blob/7b09013a698dbe1d3a722183c4d5a998b5ca8970/thoth/storages/graph/models.py#L95-L96

**Comment by fridex** [comment]
Related issue when syncing data:


```python
/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/sql/crud.py:799: SAWarning: Column 'has_artifact.python_package_version_entity_id' is marked as a member of the primary key for table 'has_artifact', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.  Primary key columns typically may not store NULL. Note that as of SQLAlchemy 1.1, 'autoincrement=True' must be indicated explicitly for composite (e.g. multicolumn) primary keys if AUTO_INCREMENT/SERIAL/IDENTITY behavior is expected for one of the columns in the primary key. CREATE TABLE statements are impacted by this change as well on most backends.
  util.warn(msg)
Traceback (most recent call last):
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "python_package_version_entity_id" violates not-null constraint
DETAIL:  Failing row contains (1, 1, 1, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fpokorny/git/thoth-station/storages/thoth/storages/graph/models_base.py", line 52, in get_or_create
    session.commit()
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
    self._flush(objects)
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
    flush_context.execute()
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1138, in _emit_insert_statements
    statement, params
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "python_package_version_entity_id" violates not-null constraint
DETAIL:  Failing row contains (1, 1, 1, null).

[SQL: INSERT INTO has_artifact (python_package_version_id, python_artifact_id) VALUES (%(python_package_version_id)s, %(python_artifact_id)s) RETURNING has_artifact.id]
[parameters: {'python_package_version_id': 1, 'python_artifact_id': 1}]
(Background on this error at: http://sqlalche.me/e/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test.py", line 18, in <module>
    graph.sync_solver_result(json.loads(Path("hexsticker.json").read_text()))
  File "/home/fpokorny/git/thoth-station/storages/thoth/storages/graph/postgres.py", line 3381, in sync_solver_result
    python_package_version_id=python_package_version.id,
  File "/home/fpokorny/git/thoth-station/storages/thoth/storages/graph/models_base.py", line 62, in get_or_create
    return session.query(cls).filter_by(**kwargs).one(), True
  File "/home/fpokorny/.local/share/virtualenvs/storages-SBQoiUiK/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3299, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
                                                              
```
