### ISSUE TITLE
type object 'PackageVersion' has no attribute 'normalize_python_package_name'

### ISSUE THREAD

**Issue by goern** [thoth-station/storages#1175]
**Describe the bug**
running some code `Package Releases Pull Updates v0.7.0-dev+thoth_storage.0.19.12+thoth_python.0.5.0-dev+thoth_messaging.0.2.0-dev`:
```
Traceback (most recent call last):
  File "/home/goern/.local/share/virtualenvs/package-releases-job-FexU2_xA/lib/python3.6/site-packages/mode/services.py", line 762, in _execute_task
    await task
  File "./pull_updates.py", line 193, in _background_task
    only_if_package_seen=0,
  File "/home/goern/Work/thoth-station/storages/thoth/storages/graph/postgres.py", line 3818, in create_python_package_version_entity
    package_name = self.normalize_python_package_name(package_name)
  File "/home/goern/Work/thoth-station/storages/thoth/storages/graph/postgres.py", line 226, in normalize_python_package_name
    return PackageVersion.normalize_python_package_name(package_name)
AttributeError: type object 'PackageVersion' has no attribute 'normalize_python_package_name'
```

**Expected behavior**
`normalize_python_package_name` is available for `PackageVersion`

**Additional context**
n/a

**Comment by fridex** [comment]
Hm, the method is present:

https://github.com/thoth-station/python/blob/b0e57d72ea9aaa901b3c9e819f9ef50c20d23bfb/thoth/python/package_version.py#L98-L103

Looking at the version string, `thoth-storages` is it it's most recent version `thoth_storage.0.19.12`. Based on the path to `postgres.py`, are you using the most recent version which is reported in the version string?

**Comment by goern** [comment]
ja, just rebased to master, problem persists.

**Comment by goern** [comment]
maybe it is with my version of thoth.python, I will have a closer look.

**Comment by goern** [comment]
my fault
