### ISSUE TITLE
Adjust syncing logic for syncing failed adviser runs

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#1261]
As adviser report has changed, we should adjust adviser syncing logic to tackle new JSON output format also when syncing failures:

```
---> Running application from Python script (app.py) ...
--
  | 2019-11-13 10:23:04,835 [1] INFO     root:123: Setting up logging to a Sentry instance 'sentry.io/1298083', environment 'thoth-psi-stage'
  | 2019-11-13 10:23:04,839 [1] INFO     root:160: Logging to rsyslog endpoint is turned off
  | 2019-11-13 10:23:04,840 [1] INFO     thoth.graph_sync_job:238: graph-sync-job v0.6.0+thoth_storage.0.19.18+thoth_common.0.9.14 starting...
  | context = migration.MigrationContext.configure(self._engine)
  | 2019-11-13 10:23:04,885 [1] INFO     alembic.runtime.migration:154: Context impl PostgresqlImpl.
  | 2019-11-13 10:23:04,885 [1] INFO     alembic.runtime.migration:161: Will assume transactional DDL.
  | 2019-11-13 10:23:05,160 [1] INFO     thoth.storages.sync:74: Syncing adviser document from https://s3.upshift.redhat.com/  with id 'adviser-d51718c7beb1343d' to graph
  | 2019-11-13 10:23:05,197 [1] WARNING  thoth.storages.graph.postgres:5049: No origin stated in the adviser result 'adviser-d51718c7beb1343d'
  | 2019-11-13 10:23:05,332 [1] CRITICAL root:101: Traceback (most recent call last):
  | File "app.py", line 239, in <module>
  | cli()
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 764, in __call__
  | return self.main(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 717, in main
  | rv = self.invoke(ctx)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 956, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 555, in invoke
  | return callback(*args, **kwargs)
  | File "app.py", line 219, in cli
  | is_local=local_file,
  | File "app.py", line 119, in _do_sync
  | is_local=is_local,
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 509, in sync_documents
  | stats_change = handler(to_sync_document_id, force=force, graceful=graceful, graph=graph)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 85, in sync_adviser_documents
  | graph.sync_adviser_result(document)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 5094, in sync_adviser_result
  | for idx, result in enumerate(document["result"]["report"]):
  | TypeError: 'NoneType' object is not iterable
  | Sentry is attempting to send 1 pending error messages
```

Adviser result `adviser-d51718c7beb1343d` can be found in the Ceph bucket in stage environment.

**Comment by pacospace** [comment]
@fridex is still relevant?

**Comment by fridex** [comment]
> @fridex is still relevant?

Yes.

**Comment by pacospace** [comment]
> > @fridex is still relevant?
> 
> Yes.

Do you have that example that fails?

I tested with `adviser-85e14039`

```
No s2i flag stated in the adviser result 'adviser-85e14039'
No report found in 'adviser-85e14039'
processed, synced, skipped, failed = (1, 1, 0, 0)

```

**Comment by pacospace** [comment]
```
            # Output stacks - advised stacks
            if not document["result"].get("report", {}):
                _LOGGER.warning("No report found in %r", adviser_document_id)
                adviser_run, _ = AdviserRun.get_or_create(session, **attributes, need_re_run=need_re_run)
                return
```

we introduced this logic when we added `advisere_re_run` flag

**Comment by fridex** [comment]
Oh, nice. I do not recall this being fixed already. :+1: 

Then we can close this. Feel free to reopen if the issue persists.
