### ISSUE TITLE
Exception spotted when generating documentation

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#1365]
**Describe the bug**

I spotted an exception being raised when documentation is generated.

**To Reproduce**

Run documentation creation and see exception:

```
WARNING: autodoc: failed to import module 'env' from module 'thoth.storages.data.alembic'; the following exception was raised:
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/storages-RKqARpjh/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/home/user/.local/share/virtualenvs/storages-RKqARpjh/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/clones/storages/thoth/storages/data/alembic/env.py", line 10, in <module>
    config = context.config
AttributeError: module 'alembic.context' has no attribute 'config'
```

**Comment by goern** [comment]
@fridex is this still valid?

**Comment by fridex** [comment]
I think we can close this.
