### ISSUE TITLE
Some solver results fail to sync due to differences in version strings

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#1415]
**Describe the bug**

It looks like some of the solver results failed to sync with the traceback attached. The reason behind it seems to be different version identifiers on PyPI and version reported back by solver.

**To Reproduce**
1. Check result of solver in stage environment `solver-fedora-31-py37-5abcbdfa` and result of `solver-fedora-31-py37-4218160b` solvers in stage environment:

`solver-fedora-31-py37-4218160b`:

```json
    "unresolved": [
      {
        "index_url": "https://pypi.org/simple",
        "is_provided_package": true,
        "is_provided_package_version": false,
        "package_name": "xonsh",
        "version_spec": "==0.9.13.dev1"
      }
    ]
```

`solver-fedora-31-py37-5abcbdfa`:
```json
        "index_url": "https://pypi.org/simple",
        "package_name": "xonsh",
        "package_version": "0.9.13.dev1",
        "package_version_requested": "0.9.13",
        "sha256": [
          "3e24f901d0c7f650485bc023c08b9b16f264271113990b107af743f3efa3950c"
        ]
```
2. install xonsh==0.9.13
3. run `python3 -c "import xonsh; print(xonsh.__version__)"` which outputs "`0.9.13.dev1`"

**Expected behavior**

As there is inconsistency on PyPI itself, its not clear which version should be reported. As pip will work with version 0.9.13 (expected), we should probably treat it as 0.9.13. 

**Additional context**

```

---> Running application from Python script (app.py) ...
--
  | 2020-01-02 08:50:07,725 [1] INFO     root:224: Setting up logging to a Sentry instance 'sentry.io/1298083', environment 'thoth-psi-stage' and integrations ['SqlalchemyIntegration']
  | 2020-01-02 08:50:07,752 [1] INFO     root:261: Logging to rsyslog endpoint is turned off
  | 2020-01-02 08:50:07,753 [1] INFO     thoth.graph_sync_job:238: graph-sync-job v0.6.0+thoth_storage.0.19.27+thoth_common.0.9.22 starting...
  | 2020-01-02 08:50:07,818 [1] INFO     alembic.runtime.migration:154: Context impl PostgresqlImpl.
  | 2020-01-02 08:50:07,818 [1] INFO     alembic.runtime.migration:161: Will assume transactional DDL.
  | 2020-01-02 08:50:07,828 [1] WARNING  thoth.storages.graph.postgres:227: Database schema is not up to date, you might encounter issues when manipulating with the database
  | 2020-01-02 08:50:08,189 [1] INFO     thoth.storages.sync:135: Syncing solver document from 'https://s3.upshift.redhat.com/'  with id 'solver-fedora-31-py37-4218160b' to graph
  | 2020-01-02 08:50:08,230 [1] INFO     thoth.storages.graph.postgres:4390: Syncing solver result of package 'xonsh' in version '0.9.13.dev1' from 'https://pypi.org/simple'  solved by {'os_name': 'fedora', 'os_version': '31', 'python_version': '3.7'}
  | 2020-01-02 08:50:08,395 [1] WARNING  thoth.storages.graph.models_base:60: Integrity error on creating a new record; this can be due to concurrent writes to database, recovering (attributes: {'package_name': 'xonsh', 'package_version': '0.9.13.dev1', 'python_package_index_id': 1, 'os_name': 'fedora', 'os_version': '31', 'python_version': '3.7', 'entity_id': 119671, 'python_package_metadata_id': 30911}): (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "python_package_version_package_name_package_version_python__key"
  | DETAIL:  Key (package_name, package_version, python_package_index_id, os_name, os_version, python_version)=(xonsh, 0.9.13.dev1, 1, fedora, 31, 3.7) already exists.
  | [SQL: INSERT INTO python_package_version (package_name, package_version, os_name, os_version, python_version, entity_id, python_package_index_id, python_package_metadata_id) VALUES (%(package_name)s, %(package_version)s, %(os_name)s, %(os_version)s, %(python_version)s, %(entity_id)s, %(python_package_index_id)s, %(python_package_metadata_id)s) RETURNING python_package_version.id]
  | [parameters: {'package_name': 'xonsh', 'package_version': '0.9.13.dev1', 'os_name': 'fedora', 'os_version': '31', 'python_version': '3.7', 'entity_id': 119671, 'python_package_index_id': 1, 'python_package_metadata_id': 30911}]
  | (Background on this error at: http://sqlalche.me/e/gkpj )
  | 2020-01-02 08:50:08,562 [1] CRITICAL root:101: Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
  | cursor, statement, parameters, context
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
  | cursor.execute(statement, parameters)
  | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "python_package_version_package_name_package_version_python__key"
  | DETAIL:  Key (package_name, package_version, python_package_index_id, os_name, os_version, python_version)=(xonsh, 0.9.13.dev1, 1, fedora, 31, 3.7) already exists.
  | The above exception was the direct cause of the following exception:
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/models_base.py", line 52, in get_or_create
  | session.commit()
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
  | self.transaction.commit()
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 494, in commit
  | self._prepare_impl()
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
  | self.session.flush()
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
  | self._flush(objects)
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
  | transaction.rollback(_capture_exception=True)
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
  | compat.reraise(exc_type, exc_value, exc_tb)
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
  | raise value
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
  | flush_context.execute()
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
  | rec.execute(self)
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
  | uow,
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
  | insert,
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1137, in _emit_insert_statements
  | statement, params
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
  | return meth(self, multiparams, params)
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
  | return connection._execute_clauseelement(self, multiparams, params)
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
  | distilled_params,
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
  | e, statement, parameters, cursor, context
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
  | util.raise_from_cause(sqlalchemy_exception, exc_info)
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
  | reraise(type(exception), exception, tb=exc_tb, cause=cause)
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
  | raise value.with_traceback(tb)
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
  | cursor, statement, parameters, context
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
  | cursor.execute(statement, parameters)
  | sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "python_package_version_package_name_package_version_python__key"
  | DETAIL:  Key (package_name, package_version, python_package_index_id, os_name, os_version, python_version)=(xonsh, 0.9.13.dev1, 1, fedora, 31, 3.7) already exists.
  | [SQL: INSERT INTO python_package_version (package_name, package_version, os_name, os_version, python_version, entity_id, python_package_index_id, python_package_metadata_id) VALUES (%(package_name)s, %(package_version)s, %(os_name)s, %(os_version)s, %(python_version)s, %(entity_id)s, %(python_package_index_id)s, %(python_package_metadata_id)s) RETURNING python_package_version.id]
  | [parameters: {'package_name': 'xonsh', 'package_version': '0.9.13.dev1', 'os_name': 'fedora', 'os_version': '31', 'python_version': '3.7', 'entity_id': 119671, 'python_package_index_id': 1, 'python_package_metadata_id': 30911}]
  | (Background on this error at: http://sqlalche.me/e/gkpj )
  | During handling of the above exception, another exception occurred:
  | Traceback (most recent call last):
  | File "app.py", line 239, in <module>
  | cli()
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 764, in __call__
  | return self.main(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 717, in main
  | rv = self.invoke(ctx)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 956, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 555, in invoke
  | return callback(*args, **kwargs)
  | File "app.py", line 219, in cli
  | is_local=local_file,
  | File "app.py", line 119, in _do_sync
  | is_local=is_local,
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 520, in sync_documents
  | is_local=is_local
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 139, in sync_solver_documents
  | graph.sync_solver_result(document)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 4438, in sync_solver_result
  | metadata=package_metadata
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 3627, in _create_python_package_version
  | python_package_metadata_id=metadata.id if metadata else None
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/models_base.py", line 62, in get_or_create
  | return session.query(cls).filter_by(**kwargs).one(), True
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3332, in one
  | raise orm_exc.NoResultFound("No row was found for one()")
  | sqlalchemy.orm.exc.NoResultFound: No row was found for one()
  | Sentry is attempting to send 1 pending error messages
  | Waiting up to 2 seconds
  | Press Ctrl-C to quit


```

**Comment by fridex** [comment]
https://pypi.org/project/xonsh/0.9.13/

**Comment by fridex** [comment]
It seems to be even more wild for some of the packages:

```json
        "package_name": "rq",
        "package_version": "0.0.0",
        "package_version_requested": "0.3.3",
        "sha256": [
```
