### ISSUE TITLE
TypeError: _create_python_software_stack() got an unexpected keyword argument 'sync_only_entity'

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#1428]
```
  | ---> Running application from Python script (app.py) ...
-- | --
  | 2020-01-06 04:58:15,510 [1] INFO     root:224: Setting up logging to a Sentry instance 'sentry.io/1298083', environment 'thoth-psi-stage' and integrations ['SqlalchemyIntegration']
  | 2020-01-06 04:58:15,519 [1] INFO     root:261: Logging to rsyslog endpoint is turned off
  | 2020-01-06 04:58:15,520 [1] INFO     thoth.graph_sync_job:238: graph-sync-job v0.6.0+thoth_storage.0.20.2+thoth_common.0.9.22 starting...
  | 2020-01-06 04:58:15,604 [1] INFO     alembic.runtime.migration:154: Context impl PostgresqlImpl.
  | 2020-01-06 04:58:15,604 [1] INFO     alembic.runtime.migration:161: Will assume transactional DDL.
  | 2020-01-06 04:58:15,992 [1] INFO     thoth.storages.sync:82: Syncing adviser document from 'https://s3.upshift.redhat.com/'  with id 'adviser-5b703358' to graph
  | 2020-01-06 04:58:16,030 [1] WARNING  thoth.storages.graph.postgres:4716: No origin stated in the adviser result 'adviser-5b703358'
  | 2020-01-06 04:58:16,031 [1] WARNING  thoth.storages.graph.postgres:4719: No s2i flag stated in the adviser result 'adviser-5b703358'
  | 2020-01-06 04:58:16,158 [1] CRITICAL root:101: Traceback (most recent call last):
  | File "app.py", line 239, in <module>
  | cli()
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 764, in __call__
  | return self.main(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 717, in main
  | rv = self.invoke(ctx)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 956, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 555, in invoke
  | return callback(*args, **kwargs)
  | File "app.py", line 219, in cli
  | is_local=local_file,
  | File "app.py", line 119, in _do_sync
  | is_local=is_local,
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 520, in sync_documents
  | is_local=is_local
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 86, in sync_adviser_documents
  | graph.sync_adviser_result(document)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 4738, in sync_adviser_result
  | sync_only_entity=True
  | TypeError: _create_python_software_stack() got an unexpected keyword argument 'sync_only_entity'

```

**Comment by fridex** [comment]
Observed in stage - `adviser-5b703358`
