### ISSUE TITLE
Failed to validate dependency monkey result schema

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#1468]
**Describe the bug**

```

2020-01-10 08:19:46,731 [26] ERROR    thoth.result_api:1891: Exception on /api/v1/dependency-monkey-report [POST]
--
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/result_base.py", line 99, in store_document
  | self.SCHEMA(document)
  | File "/opt/app-root/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 272, in __call__
  | return self._compiled([], data)
  | File "/opt/app-root/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
  | return base_validate(path, iteritems(data), out)
  | File "/opt/app-root/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
  | raise er.MultipleInvalid(errors)
  | voluptuous.error.MultipleInvalid: expected str for dictionary value @ data['metadata']['document_id']
  | The above exception was the direct cause of the following exception:
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
  | response = self.full_dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
  | rv = self.handle_user_exception(e)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
  | reraise(exc_type, exc_value, tb)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
  | raise value
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
  | rv = self.dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
  | return self.view_functions[rule.endpoint](**req.view_args)
  | File "/opt/app-root/src/wsgi.py", line 105, in post_dependency_monkey_report
  | document_id = adapter.store_document(request.json)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/result_base.py", line 101, in store_document
  | raise SchemaError("Failed to validate document schema") from exc
  | thoth.storages.exceptions.SchemaError: Failed to validate document schema
  | 172.54.34.1 - - [10/Jan/2020:08:19:46 +0000] "POST /api/v1/dependency-monkey-report HTTP/1.1" 500 290 "-" "python-requests/2.22.0"
  | 2020-01-10 08:19:47,700 [26] ERROR    thoth.result_api:1891: Exception on /api/v1/dependency-monkey-report [POST]
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/result_base.py", line 99, in store_document
  | self.SCHEMA(document)
  | File "/opt/app-root/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 272, in __call__
  | return self._compiled([], data)
  | File "/opt/app-root/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
  | return base_validate(path, iteritems(data), out)
  | File "/opt/app-root/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
  | raise er.MultipleInvalid(errors)
  | voluptuous.error.MultipleInvalid: expected str for dictionary value @ data['metadata']['document_id']
  | The above exception was the direct cause of the following exception:
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
  | response = self.full_dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
  | rv = self.handle_user_exception(e)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
  | reraise(exc_type, exc_value, tb)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
  | raise value
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
  | rv = self.dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
  | return self.view_functions[rule.endpoint](**req.view_args)
  | File "/opt/app-root/src/wsgi.py", line 105, in post_dependency_monkey_report
  | document_id = adapter.store_document(request.json)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/result_base.py", line 101, in store_document
  | raise SchemaError("Failed to validate document schema") from exc
  | thoth.storages.exceptions.SchemaError: Failed to validate document schema

```

**Comment by fridex** [comment]
Fixed. The issue was in old dependency-monkey template installed.
