### ISSUE TITLE
sqlalchemy.exc.InternalError: (psycopg2.errors.DataCorrupted)

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/storages#1586]
**Describe the bug**

**To Reproduce**
call `graph.get_python_package_hashes_sha256("setuptools", "0.6b4", "https://pypi.org/simple")`
**Expected behavior**
Returns a list of package hashes for "setuptools-0.6b4"

**Screenshots**
```bash
DEBUG:https://pypi.org:443  "GET /pypi/setuptools/0.6b4/json HTTP/1.1" 200 139978
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DataCorrupted: could not read block 412 in file "base/12406/41007": read only 0 of 8192 bytes
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "app.py", line 80, in <module>
    main()
  File "app.py", line 71, in main
    stored_hashes = sorted(graph.get_python_package_hashes_sha256(pkg_ver[0], pkg_ver[1], pkg_ver[2]))
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 2635, in get_python_package_hashes_sha256
    result = query.all()
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3233, in all
    return list(self)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3389, in __iter__
    return self._execute_and_instances(context)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3414, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.DataCorrupted) could not read block 412 in file "base/12406/41007": read only 0 of 8192 bytes
[SQL: SELECT python_artifact.artifact_hash_sha256 AS python_artifact_artifact_hash_sha256 
FROM python_package_version_entity JOIN python_package_index ON python_package_index.id = python_package_version_entity.python_package_index_id JOIN has_artifact ON python_package_version_entity.id = has_artifact.python_package_version_entity_id JOIN python_artifact ON python_artifact.id = has_artifact.python_artifact_id 
WHERE python_package_version_entity.package_name = %(package_name_1)s AND python_package_version_entity.package_version = %(package_version_1)s AND python_package_index.url = %(url_1)s]
[parameters: {'package_name_1': 'setuptools', 'package_version_1': '0.6b4', 'url_1': 'https://pypi.org/simple' }]
(Background on this error at: http://sqlalche.me/e/2j85 )
```

**Comment by KPostOffice** [comment]
This error does not occur locally with the most recent pg-dump

**Comment by fridex** [comment]
> This error does not occur locally with the most recent pg-dump

Which version of pg-dump have you used?

**Comment by KPostOffice** [comment]
I just realized I ran `test` not the actual sieve

**Comment by fridex** [comment]
> I just realized I ran `test` not the actual job
> 
> However, it does work with `pg_dump-20-02-11-00-01-54`

The dump is from today, the exception was spotted yesterday. Seems like we can dump correctly but some issue raises in the cluster.

Is the issue still replicable in the cluster for the same query?

**Comment by KPostOffice** [comment]
I ran it again in the cluster and the same issue persists today.

**Comment by KPostOffice** [comment]
https://github.com/thoth-station/storages/blob/975bbf31add9a2b6265f417739cdfaa622742b85/thoth/storages/graph/postgres.py#L2835

**Comment by goern** [comment]
ping @KPostOffice

**Comment by KPostOffice** [comment]
https://access.crunchydata.com/documentation/amcheck-next/1.5/

This seems like an issue which we can work on detecting outside of errors like this but will require intervention to restore data.  One option might be to periodically call `amcheck` and determine what data has been corrupted, then come up with a standardized way to recover the data or safely remove it from the DB and then schedule some jobs to get the data back.

**Comment by KPostOffice** [comment]
https://docs.google.com/document/d/1onhwI_3GGLfmAtZ74WDij_03kCk3Fn4ZoU0iDxCJkq4/edit

I was able to do this locally. I haven't been able to intentionally create an issue but this should be able to alert us to corruption within the database if we run this periodically

Once this is implemented we have to come up with some way of keeping track of what was removed from the database or what has been done since the last backup to try to quickly get the database up to date.

**Comment by fridex** [comment]
How long does it take to execute? Can we turn it into an alert?

**Comment by KPostOffice** [comment]
It take about 10-15 seconds locally

**Comment by fridex** [comment]
> It take about 10-15 seconds locally

Sounds reasonable to add it.

CC @pacospace

**Comment by pacospace** [comment]
> > It take about 10-15 seconds locally
> 
> Sounds reasonable to add it.
> 
> CC @pacospace

@KPostOffice Great!! I will embed this work and have a metric and alarm!!

**Comment by goern** [comment]
ping @KPostOffice

**Comment by pacospace** [comment]
> ping @KPostOffice

created card for this error https://github.com/thoth-station/storages/issues/1885

**Comment by fridex** [comment]
The discussion has been moved to the linked issues. Thanks! :+1:
