### ISSUE TITLE
Missing database migration to introduce build_log_analyzer_run

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#1589]
**Describe the bug**

There is missing database migration for https://github.com/thoth-station/storages/pull/1509/files.

**Screenshots**

```
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "build_log_analyzer_run" does not exist
LINE 2: FROM build_log_analyzer_run
             ^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/app-root/src/wsgi.py", line 89, in func_wrapper
    job()
  File "</opt/app-root/lib/python3.6/site-packages/decorator.py:decorator-gen-8>", line 2, in get_tot_records_count
  File "/opt/app-root/src/thoth/metrics_exporter/jobs/base.py", line 41, in register_metric_job
    method(*args, **kwargs)
  File "/opt/app-root/src/thoth/metrics_exporter/jobs/db.py", line 50, in get_tot_records_count
    main_models_record_count = sum(cls.graph().get_main_table_count().values())
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 4759, in get_main_table_count
    result[main_model.__tablename__] = session.query(func.count(main_model.id)).scalar()
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3377, in scalar
    ret = self.one()
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3347, in one
    ret = self.one_or_none()
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3316, in one_or_none
    ret = list(self)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3389, in __iter__
    return self._execute_and_instances(context)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3414, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "build_log_analyzer_run" does not exist
LINE 2: FROM build_log_analyzer_run
             ^
[SQL: SELECT count(build_log_analyzer_run.id) AS count_1 
FROM build_log_analyzer_run]
(Background on this error at: http://sqlalche.me/e/f405 )
```

**Comment by fridex** [comment]
We just forgot to run the migration, closing...
