### ISSUE TITLE
Noticed an alembic hash mismatch when executed the init-job on initialized DB .

### ISSUE THREAD

**Issue by harshad16** [thoth-station/storages#1608]
**Describe the bug**
Noticed an alembic hash mismatch when executed the init-job which initializes in the prod environment.

**To Reproduce**
1. Manually initialize the environment.
2. Run init-job in the environment.

**Expected behavior**
Run without interruptions. 

**Additional context**
```
﻿---> Running application from Python script (app.py) ...
2020-02-19 05:14:20,572 [1] INFO     root:224: Setting up logging to a Sentry instance 'sentry.io/129', environment 'thoth-moc-prod' and integrations ['SqlalchemyIntegration']
2020-02-19 05:14:20,631 [1] INFO     root:261: Logging to rsyslog endpoint is turned off
2020-02-19 05:14:20,793 [1] INFO     alembic.runtime.migration:154: Context impl PostgresqlImpl.
2020-02-19 05:14:20,794 [1] INFO     alembic.runtime.migration:161: Will assume transactional DDL.
2020-02-19 05:14:20,837 [1] WARNING  thoth.storages.graph.postgres:227: Database schema is not up to date, you might encounter issues when manipulating with the database
2020-02-19 05:14:20,838 [1] INFO     thoth.init_job:227: Initializing schema
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
CRITI [root] Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/alembic/script/base.py", line 162, in _catch_revision_errors
    yield
  File "/opt/app-root/lib/python3.6/site-packages/alembic/script/base.py", line 364, in _upgrade_revs
    revs = list(revs)
  File "/opt/app-root/lib/python3.6/site-packages/alembic/script/revision.py", line 765, in _iterate_revisions
    requested_lowers = self.get_revisions(lower)
  File "/opt/app-root/lib/python3.6/site-packages/alembic/script/revision.py", line 319, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/opt/app-root/lib/python3.6/site-packages/alembic/script/revision.py", line 319, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/opt/app-root/lib/python3.6/site-packages/alembic/script/revision.py", line 324, in get_revisions
    for rev_id in resolved_id
  File "/opt/app-root/lib/python3.6/site-packages/alembic/script/revision.py", line 324, in <genexpr>
    for rev_id in resolved_id
  File "/opt/app-root/lib/python3.6/site-packages/alembic/script/revision.py", line 397, in _revision_for_ident
    resolved_id,
alembic.script.revision.ResolutionError: No such revision or branch '0c8eab5d4197'
```

**Comment by pacospace** [comment]
@harshad16 is still relevant? or we can close this? I didn't have this issue initializing the database.

**Comment by harshad16** [comment]
I think this solved with fixes in storages and new updates.
Thanks for closing.
