### ISSUE TITLE
Edge property cannot have set/list cardinality

### ISSUE THREAD

**Issue by goern** [thoth-station/storages#161]
```

[2018-10-12 08:22:22 +0000] [30] [ERROR] Exception in worker process
--
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
  | worker.init_process()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
  | self.load_wsgi()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
  | self.wsgi = self.app.wsgi()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
  | self.callable = self.load()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
  | return self.load_wsgiapp()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
  | return util.import_app(self.app_uri)
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
  | __import__(module)
  | File "/opt/app-root/src/wsgi.py", line 29, in <module>
  | from thoth.storages import AdvisersResultsStore
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/__init__.py", line 25, in <module>
  | from .graph import GraphDatabase
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/__init__.py", line 3, in <module>
  | from .janusgraph import GraphDatabase
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py", line 38, in <module>
  | from .models import ALL_MODELS
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/models.py", line 133, in <module>
  | class Observed(EdgeBase):
  | File "/opt/app-root/lib/python3.6/site-packages/goblin/element.py", line 41, in __new__
  | 'Edge property cannot have set/list cardinality')
  | goblin.exception.MappingError: Edge property cannot have set/list cardinality


```

**Comment by fridex** [comment]
Agh, accidentally committed fix to master https://github.com/thoth-station/storages/commit/55888efbb095189198bb3f7e5feb055cb0cc3e4f sorry about it.
