### ISSUE TITLE
Schema initialization or any query fails on management-api deployed in test

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#1704]
**Describe the bug**

```
>>> graph.connect()
Database schema is not up to date, you might encounter issues when manipulating with the database
>>> graph.initialize_schema()
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidForeignKey: there is no unique constraint matching given keys for referenced table "adviser_run"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 310, in initialize_schema
    command.upgrade(alembic_cfg, "head")
  File "/opt/app-root/lib/python3.6/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/opt/app-root/lib/python3.6/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/app-root/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/app-root/lib/python3.6/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/data/alembic/env.py", line 80, in <module>
    run_migrations_online()
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/data/alembic/env.py", line 74, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/app-root/lib/python3.6/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/app-root/lib/python3.6/site-packages/alembic/runtime/migration.py", line 520, in run_migrations
    step.migration_fn(**kw)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/data/alembic/versions/74254b596f00_added_new_table_to_link_adviser_run_and_.py", line 26, in upgrade
    sa.PrimaryKeyConstraint('adviser_run_id', 'python_package_version_entity_id')
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/opt/app-root/lib/python3.6/site-packages/alembic/operations/ops.py", line 1252, in create_table
    return operations.invoke(op)
  File "/opt/app-root/lib/python3.6/site-packages/alembic/operations/base.py", line 374, in invoke
    return fn(self, operation)
  File "/opt/app-root/lib/python3.6/site-packages/alembic/operations/toimpl.py", line 101, in create_table
    operations.impl.create_table(table)
  File "/opt/app-root/lib/python3.6/site-packages/alembic/ddl/impl.py", line 258, in create_table
    self._exec(schema.CreateTable(table))
  File "/opt/app-root/lib/python3.6/site-packages/alembic/ddl/impl.py", line 140, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1046, in _execute_ddl
    compiled,
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidForeignKey) there is no unique constraint matching given keys for referenced table "adviser_run"

[SQL:
CREATE TABLE has_unresolved (
        adviser_run_id INTEGER NOT NULL,
        python_package_version_entity_id INTEGER NOT NULL,
        PRIMARY KEY (adviser_run_id, python_package_version_entity_id),
        FOREIGN KEY(adviser_run_id) REFERENCES adviser_run (id) ON DELETE CASCADE,
        FOREIGN KEY(python_package_version_entity_id) REFERENCES python_package_version_entity (id) ON DELETE CASCADE
)

]
(Background on this error at: http://sqlalche.me/e/f405)
>>> from thoth.storages import __version__
>>> __version__
'0.22.7'
>>>
```

**Comment by pacospace** [comment]
I cannot replicate that error locally, I'm using `pg_dump-20-03-27-00-02-11.sql`

**Comment by pacospace** [comment]
The issue seems to be duplicates rows in the database, due to copy of data during restore of the database in test environment. The data should be deleted before, otherwise, copies of records will be created and this will create issues for records that need to be unique (e.g adviser run).

**Comment by harshad16** [comment]
Test database restore was having an issue, due to resources. 
It prompts not enough disk. 

I have created a ceph based PVC with storage 20Gb in Test.
And Restore the database from stage dump.

**Comment by harshad16** [comment]
There the initialize schema from user-api.
```
(app-root) sh-4.4$ python
Python 3.6.8 (default, Oct 11 2019, 15:04:54)
[GCC 8.3.1 20190507 (Red Hat 8.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from thoth.storages import GraphDatabase
>>> g=GraphDatabase()
>>> g.connect()
Database schema is not up to date, you might encounter issues when manipulating with the database
>>> g.initialize_schema()
>>>
```
Seems like it worked.

**Comment by fridex** [comment]
@harshad16 can we close this issue?

**Comment by pacospace** [comment]
The schema in test is update now. We can move `management-api` to stage and update schema in stage as well, WDYT?

**Comment by fridex** [comment]
+1 on my side

**Comment by pacospace** [comment]
Done!
