### ISSUE TITLE
Cannot sync results of adviser with ubi-8

### ISSUE THREAD

**Issue by pacospace** [thoth-station/storages#1737]
**Describe the bug**
Graph-sync-job for adviser report is not able to sync reports where solver requested is ubi-8.

**To Reproduce**
1. Run adviser workflow with runtime environment requested ubi-8.

**Expected behavior**
Graph-sync-job syncs adviser reports with ubi-8 requested in configuration correctly.

**Screenshots**
```
{"name": "thoth.storages.graph.postgres", "levelname": "WARNING", "module": "postgres", "lineno": 286, "funcname": "connect", "created": 1587998266.3105252, "asctime": "2020-04-27 14:37:46,310", "msecs": 310.52517890930176, "relative_created": 1485.3293895721436, "process": 1, "message": "Database schema is not up to date, you might encounter issues when manipulating with the database"}
Traceback (most recent call last):
  File "app.py", line 239, in <module>
    cli()
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 219, in cli
    is_local=local_file,
  File "app.py", line 119, in _do_sync
    is_local=is_local,
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 617, in sync_documents
    to_sync_document_id, force=force, graceful=graceful, graph=graph, is_local=is_local
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 85, in sync_adviser_documents
    graph.sync_adviser_result(document)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 4924, in sync_adviser_result
    overall_score=overall_score,
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 3719, in _create_python_software_stack
    session, requirements_lock, software_environment=software_environment, sync_only_entity=is_external
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 3550, in _create_python_packages_pipfile
    f"Trying to sync package {package.name!r} in version {package.locked_version!r} "
{"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "transport", "lineno": 212, "funcname": "_send_event", "created": 1587998267.2860239, "asctime": "2020-04-27 14:37:47,286", "msecs": 286.0238552093506, "relative_created": 2460.8280658721924, "process": 1, "message": "Sending event, type:null level:error event_id:e6ba7e0c67c04459ba9547a617246c8d project:1298083 host:sentry.io"}
thoth.storages.exceptions.SolverNotRun: Trying to sync package 'absl-py' in version '0.8.1' not solved by solver-ubi-8-3.6
```

**Additional context**
It was spotted in prod by @harshad16

**Comment by pacospace** [comment]
> **Describe the bug**
> Graph-sync-job for adviser report is not able to sync reports where solver requested is ubi-8.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Run adviser workflow with runtime environment requested ubi-8.
> 
> **Expected behavior**
> Graph-sync-job syncs adviser reports with ubi-8 requested in configuration correctly.
> 
> **Screenshots**
> 
> ```
> {"name": "thoth.storages.graph.postgres", "levelname": "WARNING", "module": "postgres", "lineno": 286, "funcname": "connect", "created": 1587998266.3105252, "asctime": "2020-04-27 14:37:46,310", "msecs": 310.52517890930176, "relative_created": 1485.3293895721436, "process": 1, "message": "Database schema is not up to date, you might encounter issues when manipulating with the database"}
> Traceback (most recent call last):
>   File "app.py", line 239, in <module>
>     cli()
>   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "app.py", line 219, in cli
>     is_local=local_file,
>   File "app.py", line 119, in _do_sync
>     is_local=is_local,
>   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 617, in sync_documents
>     to_sync_document_id, force=force, graceful=graceful, graph=graph, is_local=is_local
>   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 85, in sync_adviser_documents
>     graph.sync_adviser_result(document)
>   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 4924, in sync_adviser_result
>     overall_score=overall_score,
>   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 3719, in _create_python_software_stack
>     session, requirements_lock, software_environment=software_environment, sync_only_entity=is_external
>   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 3550, in _create_python_packages_pipfile
>     f"Trying to sync package {package.name!r} in version {package.locked_version!r} "
> {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "transport", "lineno": 212, "funcname": "_send_event", "created": 1587998267.2860239, "asctime": "2020-04-27 14:37:47,286", "msecs": 286.0238552093506, "relative_created": 2460.8280658721924, "process": 1, "message": "Sending event, type:null level:error event_id:e6ba7e0c67c04459ba9547a617246c8d project:1298083 host:sentry.io"}
> thoth.storages.exceptions.SolverNotRun: Trying to sync package 'absl-py' in version '0.8.1' not solved by solver-ubi-8-3.6
> ```
> 
> **Additional context**
> It was spotted in prod by @harshad16

Thanks @harshad16, I'm going to solve it in next PR and release new version of thoth-storages :)
