### ISSUE TITLE
Some of graph-sync-solvers are failing due to duplicates

### ISSUE THREAD

**Issue by pacospace** [thoth-station/storages#1825]
**Describe the bug**
Some of graph-sync-solvers are failing.

**To Reproduce**

**Expected behavior**
Graph-sync-solver is completed successfully.

**Screenshots**
inputs
```

Name:                solver-fedora-31-py37-457c128c
Namespace:           thoth-middletier-stage
ServiceAccount:      argo
Status:              Failed
Conditions:          
 Completed           True
Created:             Thu Jun 18 12:01:36 +0200 (36 minutes ago)
Started:             Thu Jun 18 12:07:16 +0200 (30 minutes ago)
Finished:            Thu Jun 18 12:10:07 +0200 (27 minutes ago)
Duration:            2 minutes 51 seconds
Parameters:          
  ceph_bucket_prefix: data/thoth
  ceph_bucket_name:  thoth
  ceph_host:         s3.upshift.redhat.com
  deployment_name:   thoth-psi-stage
  THOTH_SOLVER_NAME: solver-fedora-31-py37
  THOTH_SOLVER_WORKFLOW_ID: solver-fedora-31-py37-457c128c
  THOTH_LOG_SOLVER:  INFO
  THOTH_SOLVER_NO_TRANSITIVE: 1
  THOTH_SOLVER_PACKAGES: pyyaml===5.3.1
  THOTH_SOLVER_INDEXES: https://pypi.org/simple
  THOTH_FORCE_SYNC:  0
  IMAGE_STREAM_REGISTRY: docker-registry.default.svc:5000
  IMAGE_STREAM_NAMESPACE: thoth-infra-stage
  IMAGE_STREAM_TAG:  latest

STEP                               TEMPLATE               PODNAME                                    DURATION  MESSAGE
 ✖ solver-fedora-31-py37-457c128c  solve-and-sync                                                                                       
 ├-✔ solverany                     solver-any/solve       solver-fedora-31-py37-457c128c-808148024   42s                                
 └-✖ graph-sync-solverany          graph-sync/graph-sync                                                       No more retries left     
   ├-✖ graph-sync-solverany(0)     graph-sync/graph-sync  solver-fedora-31-py37-457c128c-2376020894  23s       failed with exit code 1  
   ├-✖ graph-sync-solverany(1)     graph-sync/graph-sync  solver-fedora-31-py37-457c128c-698111899   22s       failed with exit code 1  
   ├-✖ graph-sync-solverany(2)     graph-sync/graph-sync  solver-fedora-31-py37-457c128c-2309204608  1m        failed with exit code 1  
   └-✖ graph-sync-solverany(3)     graph-sync/graph-sync  solver-fedora-31-py37-457c128c-3047272749  16s       failed with exit code 1  
```

logs
```
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 99, "funcname": "setup_integrations", "created": 1592475000.2825475, "asctime": "2020-06-18 10:10:00,282", "msecs": 282.5474739074707, "relative_created": 5604.233741760254, "process": 1, "message": "Setting up integrations (with default = True)"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592475000.2851512, "asctime": "2020-06-18 10:10:00,285", "msecs": 285.15124320983887, "relative_created": 5606.837511062622, "process": 1, "message": "Setting up previously not enabled integration sqlalchemy"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592475000.2854862, "asctime": "2020-06-18 10:10:00,285", "msecs": 285.48622131347656, "relative_created": 5607.17248916626, "process": 1, "message": "Setting up previously not enabled integration logging"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592475000.2855792, "asctime": "2020-06-18 10:10:00,285", "msecs": 285.5792045593262, "relative_created": 5607.265472412109, "process": 1, "message": "Setting up previously not enabled integration stdlib"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592475000.2856636, "asctime": "2020-06-18 10:10:00,285", "msecs": 285.6636047363281, "relative_created": 5607.349872589111, "process": 1, "message": "Setting up previously not enabled integration excepthook"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592475000.2857323, "asctime": "2020-06-18 10:10:00,285", "msecs": 285.7322692871094, "relative_created": 5607.418537139893, "process": 1, "message": "Setting up previously not enabled integration dedupe"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592475000.2857916, "asctime": "2020-06-18 10:10:00,285", "msecs": 285.79163551330566, "relative_created": 5607.477903366089, "process": 1, "message": "Setting up previously not enabled integration atexit"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592475000.2858477, "asctime": "2020-06-18 10:10:00,285", "msecs": 285.84766387939453, "relative_created": 5607.533931732178, "process": 1, "message": "Setting up previously not enabled integration modules"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592475000.2859166, "asctime": "2020-06-18 10:10:00,285", "msecs": 285.9165668487549, "relative_created": 5607.602834701538, "process": 1, "message": "Setting up previously not enabled integration argv"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 117, "funcname": "setup_integrations", "created": 1592475000.286063, "asctime": "2020-06-18 10:10:00,286", "msecs": 286.06295585632324, "relative_created": 5607.749223709106, "process": 1, "message": "Setting up previously not enabled integration threading"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592475000.286157, "asctime": "2020-06-18 10:10:00,286", "msecs": 286.15689277648926, "relative_created": 5607.8431606292725, "process": 1, "message": "Enabling integration sqlalchemy"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592475000.2862122, "asctime": "2020-06-18 10:10:00,286", "msecs": 286.2122058868408, "relative_created": 5607.898473739624, "process": 1, "message": "Enabling integration logging"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592475000.2862637, "asctime": "2020-06-18 10:10:00,286", "msecs": 286.26370429992676, "relative_created": 5607.94997215271, "process": 1, "message": "Enabling integration stdlib"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592475000.2863154, "asctime": "2020-06-18 10:10:00,286", "msecs": 286.3154411315918, "relative_created": 5608.001708984375, "process": 1, "message": "Enabling integration excepthook"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592475000.286365, "asctime": "2020-06-18 10:10:00,286", "msecs": 286.3650321960449, "relative_created": 5608.051300048828, "process": 1, "message": "Enabling integration dedupe"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592475000.286414, "asctime": "2020-06-18 10:10:00,286", "msecs": 286.41390800476074, "relative_created": 5608.100175857544, "process": 1, "message": "Enabling integration atexit"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592475000.2864625, "asctime": "2020-06-18 10:10:00,286", "msecs": 286.46254539489746, "relative_created": 5608.148813247681, "process": 1, "message": "Enabling integration modules"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592475000.2865112, "asctime": "2020-06-18 10:10:00,286", "msecs": 286.5111827850342, "relative_created": 5608.197450637817, "process": 1, "message": "Enabling integration argv"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "__init__", "lineno": 142, "funcname": "setup_integrations", "created": 1592475000.2865596, "asctime": "2020-06-18 10:10:00,286", "msecs": 286.5595817565918, "relative_created": 5608.245849609375, "process": 1, "message": "Enabling integration threading"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "thoth.graph_sync_job", "levelname": "INFO", "module": "app", "lineno": 238, "funcname": "<module>", "created": 1592475000.2870548, "asctime": "2020-06-18 10:10:00,287", "msecs": 287.05477714538574, "relative_created": 5608.741044998169, "process": 1, "message": "graph-sync-job v0.6.0+thoth_storage.0.22.9+thoth_common.0.13.3 starting..."}
solver-fedora-31-py37-457c128c-3047272749: {"name": "thoth.graph_sync_job", "levelname": "DEBUG", "module": "app", "lineno": 211, "funcname": "cli", "created": 1592475000.2876153, "asctime": "2020-06-18 10:10:00,287", "msecs": 287.6152992248535, "relative_created": 5609.301567077637, "process": 1, "message": "Debug mode is on"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "thoth.storages.graph.postgres", "levelname": "WARNING", "module": "postgres", "lineno": 286, "funcname": "connect", "created": 1592475000.8782866, "asctime": "2020-06-18 10:10:00,878", "msecs": 878.286600112915, "relative_created": 6199.972867965698, "process": 1, "message": "Database schema is not up to date, you might encounter issues when manipulating with the database"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "thoth.storages.graph.models_base", "levelname": "WARNING", "module": "models_base", "lineno": 60, "funcname": "get_or_create", "created": 1592475003.7479053, "asctime": "2020-06-18 10:10:03,747", "msecs": 747.9052543640137, "relative_created": 9069.591522216797, "process": 1, "message": "Integrity error on creating a new record; this can be due to concurrent writes to database, recovering (attributes: {'package_name': 'pyyaml', 'package_version': '5.3.1', 'python_package_index_id': 1, 'os_name': 'fedora', 'os_version': '31', 'python_version': '3.7', 'entity_id': 62, 'python_package_metadata_id': 160933}): (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"python_package_version_package_name_package_version_python__key\"\nDETAIL:  Key (package_name, package_version, python_package_index_id, os_name, os_version, python_version)=(pyyaml, 5.3.1, 1, fedora, 31, 3.7) already exists.\n\n[SQL: INSERT INTO python_package_version (package_name, package_version, os_name, os_version, python_version, entity_id, python_package_index_id, python_package_metadata_id, is_missing) VALUES (%(package_name)s, %(package_version)s, %(os_name)s, %(os_version)s, %(python_version)s, %(entity_id)s, %(python_package_index_id)s, %(python_package_metadata_id)s, %(is_missing)s) RETURNING python_package_version.id]\n[parameters: {'package_name': 'pyyaml', 'package_version': '5.3.1', 'os_name': 'fedora', 'os_version': '31', 'python_version': '3.7', 'entity_id': 62, 'python_package_index_id': 1, 'python_package_metadata_id': 160933, 'is_missing': False}]\n(Background on this error at: http://sqlalche.me/e/gkpj)"}
solver-fedora-31-py37-457c128c-3047272749: Traceback (most recent call last):
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
solver-fedora-31-py37-457c128c-3047272749:     cursor, statement, parameters, context
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
solver-fedora-31-py37-457c128c-3047272749:     cursor.execute(statement, parameters)
solver-fedora-31-py37-457c128c-3047272749: psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "python_package_version_package_name_package_version_python__key"
solver-fedora-31-py37-457c128c-3047272749: DETAIL:  Key (package_name, package_version, python_package_index_id, os_name, os_version, python_version)=(pyyaml, 5.3.1, 1, fedora, 31, 3.7) already exists.
solver-fedora-31-py37-457c128c-3047272749: The above exception was the direct cause of the following exception:
solver-fedora-31-py37-457c128c-3047272749: Traceback (most recent call last):
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/models_base.py", line 52, in get_or_create
solver-fedora-31-py37-457c128c-3047272749:     session.commit()
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
solver-fedora-31-py37-457c128c-3047272749:     self.transaction.commit()
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 503, in commit
solver-fedora-31-py37-457c128c-3047272749:     self._prepare_impl()
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
solver-fedora-31-py37-457c128c-3047272749:     self.session.flush()
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
solver-fedora-31-py37-457c128c-3047272749:     self._flush(objects)
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
solver-fedora-31-py37-457c128c-3047272749:     transaction.rollback(_capture_exception=True)
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
solver-fedora-31-py37-457c128c-3047272749:     exc_value, with_traceback=exc_tb,
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
solver-fedora-31-py37-457c128c-3047272749:     raise exception
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
solver-fedora-31-py37-457c128c-3047272749:     flush_context.execute()
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
solver-fedora-31-py37-457c128c-3047272749:     rec.execute(self)
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
solver-fedora-31-py37-457c128c-3047272749:     uow,
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "transport", "lineno": 212, "funcname": "_send_event", "created": 1592475004.1720107, "asctime": "2020-06-18 10:10:04,172", "msecs": 172.0106601715088, "relative_created": 9493.696928024292, "process": 1, "message": "Sending event, type:null level:error event_id:1509e8722b6b4d88babcd5db3cd8bdb7 project:1298083 host:sentry.io"}
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
solver-fedora-31-py37-457c128c-3047272749:     insert,
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
solver-fedora-31-py37-457c128c-3047272749:     statement, params
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
solver-fedora-31-py37-457c128c-3047272749:     return meth(self, multiparams, params)
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
solver-fedora-31-py37-457c128c-3047272749:     return connection._execute_clauseelement(self, multiparams, params)
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
solver-fedora-31-py37-457c128c-3047272749:     distilled_params,
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
solver-fedora-31-py37-457c128c-3047272749:     e, statement, parameters, cursor, context
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
solver-fedora-31-py37-457c128c-3047272749:     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
solver-fedora-31-py37-457c128c-3047272749:     raise exception
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
solver-fedora-31-py37-457c128c-3047272749:     cursor, statement, parameters, context
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
solver-fedora-31-py37-457c128c-3047272749:     cursor.execute(statement, parameters)
solver-fedora-31-py37-457c128c-3047272749: sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "python_package_version_package_name_package_version_python__key"
solver-fedora-31-py37-457c128c-3047272749: DETAIL:  Key (package_name, package_version, python_package_index_id, os_name, os_version, python_version)=(pyyaml, 5.3.1, 1, fedora, 31, 3.7) already exists.
solver-fedora-31-py37-457c128c-3047272749: [SQL: INSERT INTO python_package_version (package_name, package_version, os_name, os_version, python_version, entity_id, python_package_index_id, python_package_metadata_id, is_missing) VALUES (%(package_name)s, %(package_version)s, %(os_name)s, %(os_version)s, %(python_version)s, %(entity_id)s, %(python_package_index_id)s, %(python_package_metadata_id)s, %(is_missing)s) RETURNING python_package_version.id]
solver-fedora-31-py37-457c128c-3047272749: [parameters: {'package_name': 'pyyaml', 'package_version': '5.3.1', 'os_name': 'fedora', 'os_version': '31', 'python_version': '3.7', 'entity_id': 62, 'python_package_index_id': 1, 'python_package_metadata_id': 160933, 'is_missing': False}]
solver-fedora-31-py37-457c128c-3047272749: (Background on this error at: http://sqlalche.me/e/gkpj)
solver-fedora-31-py37-457c128c-3047272749: During handling of the above exception, another exception occurred:
solver-fedora-31-py37-457c128c-3047272749: Traceback (most recent call last):
solver-fedora-31-py37-457c128c-3047272749:   File "app.py", line 239, in <module>
solver-fedora-31-py37-457c128c-3047272749:     cli()
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
solver-fedora-31-py37-457c128c-3047272749:     return self.main(*args, **kwargs)
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
solver-fedora-31-py37-457c128c-3047272749:     rv = self.invoke(ctx)
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
solver-fedora-31-py37-457c128c-3047272749:     return ctx.invoke(self.callback, **ctx.params)
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
solver-fedora-31-py37-457c128c-3047272749:     return callback(*args, **kwargs)
solver-fedora-31-py37-457c128c-3047272749:   File "app.py", line 219, in cli
solver-fedora-31-py37-457c128c-3047272749:     is_local=local_file,
solver-fedora-31-py37-457c128c-3047272749:   File "app.py", line 119, in _do_sync
solver-fedora-31-py37-457c128c-3047272749:     is_local=is_local,
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 617, in sync_documents
solver-fedora-31-py37-457c128c-3047272749:     to_sync_document_id, force=force, graceful=graceful, graph=graph, is_local=is_local
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 136, in sync_solver_documents
solver-fedora-31-py37-457c128c-3047272749:     graph.sync_solver_result(document)
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 4603, in sync_solver_result
solver-fedora-31-py37-457c128c-3047272749:     python_package_metadata_id=package_metadata.id,
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 3691, in _create_python_package_version
solver-fedora-31-py37-457c128c-3047272749:     python_package_metadata_id=python_package_metadata_id,
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/models_base.py", line 62, in get_or_create
solver-fedora-31-py37-457c128c-3047272749:     return session.query(cls).filter_by(**kwargs).one(), True
solver-fedora-31-py37-457c128c-3047272749:   File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3370, in one
solver-fedora-31-py37-457c128c-3047272749:     raise orm_exc.NoResultFound("No row was found for one()")
solver-fedora-31-py37-457c128c-3047272749: sqlalchemy.orm.exc.NoResultFound: No row was found for one()
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "atexit", "lineno": 51, "funcname": "_shutdown", "created": 1592475004.1797612, "asctime": "2020-06-18 10:10:04,179", "msecs": 179.76117134094238, "relative_created": 9501.447439193726, "process": 1, "message": "atexit: got shutdown signal"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "atexit", "lineno": 55, "funcname": "_shutdown", "created": 1592475004.1800263, "asctime": "2020-06-18 10:10:04,180", "msecs": 180.02629280090332, "relative_created": 9501.712560653687, "process": 1, "message": "atexit: shutting down client"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "transport", "lineno": 320, "funcname": "flush", "created": 1592475004.1801343, "asctime": "2020-06-18 10:10:04,180", "msecs": 180.13429641723633, "relative_created": 9501.82056427002, "process": 1, "message": "Flushing HTTP transport"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "worker", "lineno": 105, "funcname": "flush", "created": 1592475004.1802065, "asctime": "2020-06-18 10:10:04,180", "msecs": 180.2065372467041, "relative_created": 9501.892805099487, "process": 1, "message": "background worker got flush request"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "worker", "lineno": 116, "funcname": "_wait_flush", "created": 1592475004.280557, "asctime": "2020-06-18 10:10:04,280", "msecs": 280.55691719055176, "relative_created": 9602.243185043335, "process": 1, "message": "0 event(s) pending on flush"}
solver-fedora-31-py37-457c128c-3047272749: Sentry is attempting to send 0 pending error messages
solver-fedora-31-py37-457c128c-3047272749: Waiting up to 2 seconds
solver-fedora-31-py37-457c128c-3047272749: Press Ctrl-C to quit
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "worker", "lineno": 109, "funcname": "flush", "created": 1592475004.4664857, "asctime": "2020-06-18 10:10:04,466", "msecs": 466.48573875427246, "relative_created": 9788.172006607056, "process": 1, "message": "background worker flushed"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "transport", "lineno": 326, "funcname": "kill", "created": 1592475004.4668002, "asctime": "2020-06-18 10:10:04,466", "msecs": 466.8002128601074, "relative_created": 9788.48648071289, "process": 1, "message": "Killing HTTP transport"}
solver-fedora-31-py37-457c128c-3047272749: {"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "worker", "lineno": 92, "funcname": "kill", "created": 1592475004.4669201, "asctime": "2020-06-18 10:10:04,466", "msecs": 466.9201374053955, "relative_created": 9788.606405258179, "process": 1, "message": "background worker got kill request"}
```

**Additional context**

**Comment by pacospace** [comment]
This should not be possible as we schedule solvers only for packages that were never been solved. @fridex any thoughts?

**Comment by fridex** [comment]
> This should not be possible as we schedule solvers only for packages that were never been solved

All graph syncs should be reentrant. I might have scheduled some solvers for already solved packages. Given the traceback, it looks like we should update thoth-storages (I cannot easily map the traceback to the current master). Let's see if the issue persists.

**Comment by pacospace** [comment]
I think we can close this issue, as we didn't spot it anymore after recreating the database. Feel free to reopen it if necessary.
