### ISSUE TITLE
Database schema cannot be updated to revision  `6389973bd8b6_remove_package_analyzer`

### ISSUE THREAD

**Issue by pacospace** [thoth-station/storages#2008]
**Describe the bug**
Schema cannot be updated.

**To Reproduce**
1. Try syncing database with alembic version: `6389973bd8b6_remove_package_analyzer`

**Expected behavior**
Update schema successfull.

**Screenshots**
```
The database schema is not in sync with library revisions, the current library revision heads: {'6389973bd8b6'}, database heads: {'84588707e6ba'}
Traceback (most recent call last):
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DependentObjectsStillExist: cannot drop table python_package_version_entity because other objects depend on it
DETAIL:  constraint package_analyzer_run_input_python_package_version_entity_i_fkey on table package_analyzer_run depends on table python_package_version_entity
HINT:  Use DROP ... CASCADE to drop the dependent objects too.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    graph.drop_all()
  File "/home/fmurdaca/work/aicoe/storages/thoth/storages/graph/postgres.py", line 322, in drop_all
    super().drop_all()
  File "/home/fmurdaca/work/aicoe/storages/thoth/storages/graph/sql_base.py", line 72, in drop_all
    self._DECLARATIVE_BASE.metadata.drop_all(self._engine)
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4582, in drop_all
    ddl.SchemaDropper, self, checkfirst=checkfirst, tables=tables
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2097, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 956, in visit_metadata
    table, drop_ok=True, _is_metadata_operation=True
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 1009, in visit_table
    self.connection.execute(DropTable(table))
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_ddl
    compiled,
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table python_package_version_entity because other objects depend on it
DETAIL:  constraint package_analyzer_run_input_python_package_version_entity_i_fkey on table package_analyzer_run depends on table python_package_version_entity
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: 
DROP TABLE python_package_version_entity]
(Background on this error at: http://sqlalche.me/e/13/2j85)
```

**Additional context**

**Comment by saisankargochhayat** [comment]
```
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table package_analyzer_run because other objects depend on it
DETAIL:  constraint investigated_file_package_analyzer_run_id_fkey on table investigated_file depends on table package_analyzer_run
```
