### ISSUE TITLE
Bug occuring when running security step - column si_aggregated_run.error does not exist

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#2072]
**Describe the bug**

```
2020-11-04 09:36:19,749 thoth.adviser.run           ERROR: Adviser raised exception: Failed to run step 'SecurityIndicatorStep' for Python package ('flask', '0.12.2', 'https://pypi.org/simple'): (psycopg2.errors.UndefinedColumn) column si_aggregated_run.error does not exist
LINE 1: ...gated_run.datetime AS si_aggregated_run_datetime, si_aggrega...
                                                             ^

[SQL: SELECT si_aggregated_run.id AS si_aggregated_run_id, si_aggregated_run.si_aggregated_run_document_id AS si_aggregated_run_si_aggregated_run_document_id, si_aggregated_run.datetime AS si_aggregated_run_datetime, si_aggregated_run.error AS si_aggregated_run_error, si_aggregated_run.severity_high_confidence_high AS si_aggregated_run_severity_high_confidence_high, si_aggregated_run.severity_high_confidence_low AS si_aggregated_run_severity_high_confidence_low, si_aggregated_run.severity_high_confidence_medium AS si_aggregated_run_severity_high_confidence_medium, si_aggregated_run.severity_high_confidence_undefined AS si_aggregated_run_severity_high_confidence_undefined, si_aggregated_run.severity_low_confidence_high AS si_aggregated_run_severity_low_confidence_high, si_aggregated_run.severity_low_confidence_low AS si_aggregated_run_severity_low_confidence_low, si_aggregated_run.severity_low_confidence_medium AS si_aggregated_run_severity_low_confidence_medium, si_aggregated_run.severity_low_confidence_undefined AS si_aggregated_run_severity_low_confidence_undefined, si_aggregated_run.severity_medium_confidence_high AS si_aggregated_run_severity_medium_confidence_high, si_aggregated_run.severity_medium_confidence_low AS si_aggregated_run_severity_medium_confidence_low, si_aggregated_run.severity_medium_confidence_medium AS si_aggregated_run_severity_medium_confidence_medium, si_aggregated_run.severity_medium_confidence_undefined AS si_aggregated_run_severity_medium_confidence_undefined, si_aggregated_run.number_of_analyzed_files AS si_aggregated_run_number_of_analyzed_files, si_aggregated_run.number_of_files_total AS si_aggregated_run_number_of_files_total, si_aggregated_run.number_of_files_with_severities AS si_aggregated_run_number_of_files_with_severities, si_aggregated_run.number_of_filtered_files AS si_aggregated_run_number_of_filtered_files, si_aggregated_run.number_of_python_files AS si_aggregated_run_number_of_python_files, si_aggregated_run.number_of_lines_with_comments_in_python_files AS si_aggregated_run_number_of_lines_with_comments_in_python_1, si_aggregated_run.number_of_blank_lines_in_python_files AS si_aggregated_run_number_of_blank_lines_in_python_files, si_aggregated_run.number_of_lines_with_code_in_python_files AS si_aggregated_run_number_of_lines_with_code_in_python_fil_2, si_aggregated_run.total_number_of_files AS si_aggregated_run_total_number_of_files, si_aggregated_run.total_number_of_lines AS si_aggregated_run_total_number_of_lines, si_aggregated_run.total_number_of_lines_with_comments AS si_aggregated_run_total_number_of_lines_with_comments, si_aggregated_run.total_number_of_blank_lines AS si_aggregated_run_total_number_of_blank_lines, si_aggregated_run.total_number_of_lines_with_code AS si_aggregated_run_total_number_of_lines_with_code 
FROM si_aggregated_run, python_package_version, python_package_index, si_aggregated 
WHERE python_package_version.package_name = %(package_name_1)s AND python_package_version.package_version = %(package_version_1)s AND python_package_index.url = %(url_1)s AND python_package_version.id = si_aggregated.python_package_version_id ORDER BY si_aggregated_run.datetime DESC 
 LIMIT %(param_1)s]
[parameters: {'package_name_1': 'flask', 'package_version_1': '0.12.2', 'url_1': 'https://pypi.org/simple', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column si_aggregated_run.error does not exist
LINE 1: ...gated_run.datetime AS si_aggregated_run_datetime, si_aggrega...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 345, in _run_steps
    step_result = step.run(state, package_version)
  File "/opt/app-root/src/thoth/adviser/steps/security_indicators.py", line 113, in run
    index_url=package_version.index.url,
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 206, in wrapped_func
    return cached_method(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 202, in cached_method
    return func(self_weak(), *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 1857, in get_si_aggregated_python_package_version
    result = query.order_by(SecurityIndicatorAggregatedRun.datetime.desc()).first()
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column si_aggregated_run.error does not exist
LINE 1: ...gated_run.datetime AS si_aggregated_run_datetime, si_aggrega...
                                                             ^

[SQL: SELECT si_aggregated_run.id AS si_aggregated_run_id, si_aggregated_run.si_aggregated_run_document_id AS si_aggregated_run_si_aggregated_run_document_id, si_aggregated_run.datetime AS si_aggregated_run_datetime, si_aggregated_run.error AS si_aggregated_run_error, si_aggregated_run.severity_high_confidence_high AS si_aggregated_run_severity_high_confidence_high, si_aggregated_run.severity_high_confidence_low AS si_aggregated_run_severity_high_confidence_low, si_aggregated_run.severity_high_confidence_medium AS si_aggregated_run_severity_high_confidence_medium, si_aggregated_run.severity_high_confidence_undefined AS si_aggregated_run_severity_high_confidence_undefined, si_aggregated_run.severity_low_confidence_high AS si_aggregated_run_severity_low_confidence_high, si_aggregated_run.severity_low_confidence_low AS si_aggregated_run_severity_low_confidence_low, si_aggregated_run.severity_low_confidence_medium AS si_aggregated_run_severity_low_confidence_medium, si_aggregated_run.severity_low_confidence_undefined AS si_aggregated_run_severity_low_confidence_undefined, si_aggregated_run.severity_medium_confidence_high AS si_aggregated_run_severity_medium_confidence_high, si_aggregated_run.severity_medium_confidence_low AS si_aggregated_run_severity_medium_confidence_low, si_aggregated_run.severity_medium_confidence_medium AS si_aggregated_run_severity_medium_confidence_medium, si_aggregated_run.severity_medium_confidence_undefined AS si_aggregated_run_severity_medium_confidence_undefined, si_aggregated_run.number_of_analyzed_files AS si_aggregated_run_number_of_analyzed_files, si_aggregated_run.number_of_files_total AS si_aggregated_run_number_of_files_total, si_aggregated_run.number_of_files_with_severities AS si_aggregated_run_number_of_files_with_severities, si_aggregated_run.number_of_filtered_files AS si_aggregated_run_number_of_filtered_files, si_aggregated_run.number_of_python_files AS si_aggregated_run_number_of_python_files, si_aggregated_run.number_of_lines_with_comments_in_python_files AS si_aggregated_run_number_of_lines_with_comments_in_python_1, si_aggregated_run.number_of_blank_lines_in_python_files AS si_aggregated_run_number_of_blank_lines_in_python_files, si_aggregated_run.number_of_lines_with_code_in_python_files AS si_aggregated_run_number_of_lines_with_code_in_python_fil_2, si_aggregated_run.total_number_of_files AS si_aggregated_run_total_number_of_files, si_aggregated_run.total_number_of_lines AS si_aggregated_run_total_number_of_lines, si_aggregated_run.total_number_of_lines_with_comments AS si_aggregated_run_total_number_of_lines_with_comments, si_aggregated_run.total_number_of_blank_lines AS si_aggregated_run_total_number_of_blank_lines, si_aggregated_run.total_number_of_lines_with_code AS si_aggregated_run_total_number_of_lines_with_code 
FROM si_aggregated_run, python_package_version, python_package_index, si_aggregated 
WHERE python_package_version.package_name = %(package_name_1)s AND python_package_version.package_version = %(package_version_1)s AND python_package_index.url = %(url_1)s AND python_package_version.id = si_aggregated.python_package_version_id ORDER BY si_aggregated_run.datetime DESC 
 LIMIT %(param_1)s]
[parameters: {'package_name_1': 'flask', 'package_version_1': '0.12.2', 'url_1': 'https://pypi.org/simple', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/src/thoth/adviser/run.py", line 76, in subprocess_run
    with_devel=with_devel, user_stack_scoring=user_stack_scoring
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 1241, in resolve
    for state in self._do_resolve_states(with_devel=with_devel, user_stack_scoring=user_stack_scoring):
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 1172, in _do_resolve_states
    with_devel=with_devel, user_stack_scoring=user_stack_scoring
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 1121, in _do_resolve_states_raw
    state_returned = self._expand_state(state, unresolved_package_tuple)
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 829, in _expand_state
    state=state, package_version=package_version, dependencies=list(chain(*dependencies.values())),
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 1055, in _expand_state_add_dependencies
    return self._run_steps(state, package_version, all_dependencies, newly_added)
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 381, in _run_steps
    ) from exc
thoth.adviser.exceptions.StepError: Failed to run step 'SecurityIndicatorStep' for Python package ('flask', '0.12.2', 'https://pypi.org/simple'): (psycopg2.errors.UndefinedColumn) column si_aggregated_run.error does not exist
LINE 1: ...gated_run.datetime AS si_aggregated_run_datetime, si_aggrega...
                                                             ^

[SQL: SELECT si_aggregated_run.id AS si_aggregated_run_id, si_aggregated_run.si_aggregated_run_document_id AS si_aggregated_run_si_aggregated_run_document_id, si_aggregated_run.datetime AS si_aggregated_run_datetime, si_aggregated_run.error AS si_aggregated_run_error, si_aggregated_run.severity_high_confidence_high AS si_aggregated_run_severity_high_confidence_high, si_aggregated_run.severity_high_confidence_low AS si_aggregated_run_severity_high_confidence_low, si_aggregated_run.severity_high_confidence_medium AS si_aggregated_run_severity_high_confidence_medium, si_aggregated_run.severity_high_confidence_undefined AS si_aggregated_run_severity_high_confidence_undefined, si_aggregated_run.severity_low_confidence_high AS si_aggregated_run_severity_low_confidence_high, si_aggregated_run.severity_low_confidence_low AS si_aggregated_run_severity_low_confidence_low, si_aggregated_run.severity_low_confidence_medium AS si_aggregated_run_severity_low_confidence_medium, si_aggregated_run.severity_low_confidence_undefined AS si_aggregated_run_severity_low_confidence_undefined, si_aggregated_run.severity_medium_confidence_high AS si_aggregated_run_severity_medium_confidence_high, si_aggregated_run.severity_medium_confidence_low AS si_aggregated_run_severity_medium_confidence_low, si_aggregated_run.severity_medium_confidence_medium AS si_aggregated_run_severity_medium_confidence_medium, si_aggregated_run.severity_medium_confidence_undefined AS si_aggregated_run_severity_medium_confidence_undefined, si_aggregated_run.number_of_analyzed_files AS si_aggregated_run_number_of_analyzed_files, si_aggregated_run.number_of_files_total AS si_aggregated_run_number_of_files_total, si_aggregated_run.number_of_files_with_severities AS si_aggregated_run_number_of_files_with_severities, si_aggregated_run.number_of_filtered_files AS si_aggregated_run_number_of_filtered_files, si_aggregated_run.number_of_python_files AS si_aggregated_run_number_of_python_files, si_aggregated_run.number_of_lines_with_comments_in_python_files AS si_aggregated_run_number_of_lines_with_comments_in_python_1, si_aggregated_run.number_of_blank_lines_in_python_files AS si_aggregated_run_number_of_blank_lines_in_python_files, si_aggregated_run.number_of_lines_with_code_in_python_files AS si_aggregated_run_number_of_lines_with_code_in_python_fil_2, si_aggregated_run.total_number_of_files AS si_aggregated_run_total_number_of_files, si_aggregated_run.total_number_of_lines AS si_aggregated_run_total_number_of_lines, si_aggregated_run.total_number_of_lines_with_comments AS si_aggregated_run_total_number_of_lines_with_comments, si_aggregated_run.total_number_of_blank_lines AS si_aggregated_run_total_number_of_blank_lines, si_aggregated_run.total_number_of_lines_with_code AS si_aggregated_run_total_number_of_lines_with_code 
FROM si_aggregated_run, python_package_version, python_package_index, si_aggregated 
WHERE python_package_version.package_name = %(package_name_1)s AND python_package_version.package_version = %(package_version_1)s AND python_package_index.url = %(url_1)s AND python_package_version.id = si_aggregated.python_package_version_id ORDER BY si_aggregated_run.datetime DESC 
 LIMIT %(param_1)s]
[parameters: {'package_name_1': 'flask', 'package_version_1': '0.12.2', 'url_1': 'https://pypi.org/simple', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)
2020-11-04 09:36:19,780 thoth.adviser.run           ERROR: Child exited with exit code 512
2020-11-04 09:36:19,783 thoth.adviser.run           ERROR: Resolution was terminated based on errors encountered; see logs for more info - https://thoth-station.ninja/j/error_logs
```

**To Reproduce**
1. Use stage environment
2. Run `thamos advise` with the following setup

```
#
# This is default Thoth configuration file placed in a root of a repo. Please adjust values listed below.

host: khemenu.thoth-station.ninja
tls_verify: false

requirements_format: pipenv

runtime_environments:
  - name: "my_project"
    recommendation_type: security
    operating_system:
      name: "rhel"
      version: "8.0"
    python_version: "3.6"
```

```
[[source]]
name = "pypi-org"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
flask = "<0.12.3"
```

3. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by fridex** [comment]
thoth-storages running in stage: `0.25.14`

**Comment by pacospace** [comment]
I think it is not a bug, storages is not udpdated: https://grafana.datahub.redhat.com/dashboard/db/thoth-component-versions?refresh=30s&orgId=1

**Comment by fridex** [comment]
Updated from management-api prior filling the bug. Maybe management-api needs an update?!

**Comment by pacospace** [comment]
We need to release new thoth-storages with latest storages 0.25.16: https://github.com/thoth-station/management-api/issues/615

**Comment by pacospace** [comment]
> Updated from management-api prior filling the bug. Maybe management-api needs an update?!

Yes exactly, opened Kebechet update issue, then we can release it :beers:

**Comment by fridex** [comment]
updated to thoth-storages 0.25.15, the issue persists

**Comment by pacospace** [comment]
> updated to thoth-storages 0.25.15, the issue persists

the feature on error in SI was introduced in 0.25.16 https://github.com/thoth-station/storages/pull/2067

**Comment by fridex** [comment]
> > updated to thoth-storages 0.25.15, the issue persists
> 
> the feature on error in SI was introduced in 0.25.16 #2067

We should scope what we expect from major/patch/minor releases. A database schema change does not sound like a patch change.

**Comment by pacospace** [comment]
> > > updated to thoth-storages 0.25.15, the issue persists
> > 
> > 
> > the feature on error in SI was introduced in 0.25.16 #2067
> 
> We should scope what we expect from major/patch/minor releases. A database schema change does not sound like a patch change.

my fault sorry :/

**Comment by fridex** [comment]
> my fault sorry :/

No sorry at all. :beers:

**Comment by fridex** [comment]
Database schema updated, the security step does not produce any errors. :+1:
