### ISSUE TITLE
Issue for one package after moving to python 3.8

### ISSUE THREAD

**Issue by pacospace** [thoth-station/storages#2126]
**Describe the bug**
Issue for one package after moving to py3.8

**To Reproduce**
1. Schedule graph-sync

**Expected behavior**
Sync finished successfully. 

**Screenshots**
```
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.395694131Z Traceback (most recent call last):
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.395694131Z   File "app.py", line 33, in <module>
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.395918039Z     from thoth.storages import __version__ as __storages__version__
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.395918039Z   File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/__init__.py", line 30, in <module>
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.395918039Z     from .graph import GraphDatabase
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.395918039Z   File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/graph/__init__.py", line 21, in <module>
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.395918039Z   File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/graph/postgres.py", line 53, in <module>
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.395918039Z     from .postgres import GraphDatabase
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.395935105Z     from thoth.python import PackageVersion
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.395935105Z   File "/opt/app-root/lib64/python3.8/site-packages/thoth/python/__init__.py", line 29, in <module>
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.396042616Z     from .aiosource import AIOSource, AsyncIterablePackages, AsyncIterableVersions, AsyncIterableArtifacts
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.396042616Z   File "/opt/app-root/lib64/python3.8/site-packages/thoth/python/aiosource.py", line 29, in <module>
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.396092618Z   File "/opt/app-root/lib64/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.396092618Z     import aiohttp
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.396336595Z     from .client import (
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.396336595Z   File "/opt/app-root/lib64/python3.8/site-packages/aiohttp/client.py", line 35, in <module>
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.396336595Z     from . import hdrs, http, payload
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.396336595Z   File "/opt/app-root/lib64/python3.8/site-packages/aiohttp/http.py", line 7, in <module>
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.396336595Z     from .http_parser import (
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.396336595Z   File "/opt/app-root/lib64/python3.8/site-packages/aiohttp/http_parser.py", line 15, in <module>
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.398407621Z     from .helpers import NO_EXTENSIONS, BaseTimerContext
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.398407621Z   File "/opt/app-root/lib64/python3.8/site-packages/aiohttp/helpers.py", line 48, in <module>
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.398407621Z     from typing_extensions import Protocol
adviser-665bae6c-3229263023: 2020-12-01T11:19:29.398407621Z ModuleNotFoundError: No module named 'typing_extensions'

```

**Additional context**

**Comment by pacospace** [comment]
Encountered already the problem because `typing_extensions` required py < 3.7 according to Pipfile.lock. I removed and recreated the Pipfile.lock in another repo and the problem was solved.) but this does not seem the same issue here as Pipfile.lock is correct

**Comment by pacospace** [comment]
```
        "typing-extensions": {
            "hashes": [
                "sha256:7cb407020f00f7bfc3cb3e7881628838e69d8f3fcab2f64742a5e76b2f841918",
                "sha256:99d4073b617d30288f569d3f13d2bd7548c3a7e4c8de87db09a9d29bb3a4a60c",
                "sha256:dafc7639cde7f1b6e1acc0f457842a83e722ccca8eef5270af2d74792619a89f"
            ],
            "markers": "python_version < '3.8'",
            "version": "==3.7.4.3"
        },
```
