### ISSUE TITLE
Some of the columns not present in kebechet_github_installations table

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/storages#2133]
**Describe the bug**
When using `graph.get_kebechet_github_installations_count_per_is_active()` method, it seems that the `kebechet_github_installations.external_python_software_stack_id` column is missing.

This is also true according to the database inspection in `pgweb`, where I can see all columns from query present except these ones:

```
kebechet_github_installations.external_python_software_stack_id
kebechet_github_installations.external_software_environment_id
kebechet_github_installations.advised_python_software_stack_id
```

**To Reproduce**
1. set up the databse with the `pg_dump-20-12-01-00-02-19` dump
2. uses `thoth.storages` as follow:
```
>>> from thoth.storages import GraphDatabase
>>> graph = GraphDatabase()
>>> graph.connect()
The database schema is not in sync with library revisions, the current library revision heads: {'e7ebfc165a96'}, database heads: {'342d45db2dc2'}
>>> graph.get_kebechet_github_installations_count_per_is_active()
```

**Expected behavior**
A valid and correct query from the `graph.get_kebechet_github_installations_count_per_is_active()` with the return value of active kebechet github installations count.

**LOG**
```
>>> graph.get_kebechet_github_installations_count_per_is_active()
Traceback (most recent call last):
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column kebechet_github_installations.external_python_software_stack_id does not exist
LINE 2: ...st_run AS kebechet_github_installations_last_run, kebechet_g...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xtuchyna/git/forks/storages/thoth/storages/graph/postgres.py", line 3482, in get_kebechet_github_installations_count_per_is_active
    session.query(KebechetGithubAppInstallations)
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3803, in count
    return self.from_self(col).scalar()
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3523, in scalar
    ret = self.one()
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3490, in one
    ret = self.one_or_none()
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
    ret = list(self)
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column kebechet_github_installations.external_python_software_stack_id does not exist
LINE 2: ...st_run AS kebechet_github_installations_last_run, kebechet_g...
                                                             ^

[SQL: SELECT count(*) AS count_1 
FROM (SELECT kebechet_github_installations.id AS kebechet_github_installations_id, kebechet_github_installations.slug AS kebechet_github_installations_slug, kebechet_github_installations.repo_name AS kebechet_github_installations_repo_name, kebechet_github_installations.private AS kebechet_github_installations_private, kebechet_github_installations.installation_id AS kebechet_github_installations_installation_id, kebechet_github_installations.is_active AS kebechet_github_installations_is_active, kebechet_github_installations.info_manager AS kebechet_github_installations_info_manager, kebechet_github_installations.pipfile_requirements_manager AS kebechet_github_installations_pipfile_requirements_manage_1, kebechet_github_installations.update_manager AS kebechet_github_installations_update_manager, kebechet_github_installations.version_manager AS kebechet_github_installations_version_manager, kebechet_github_installations.thoth_advise_manager AS kebechet_github_installations_thoth_advise_manager, kebechet_github_installations.thoth_provenance_manager AS kebechet_github_installations_thoth_provenance_manager, kebechet_github_installations.last_run AS kebechet_github_installations_last_run, kebechet_github_installations.external_python_software_stack_id AS kebechet_github_installations_external_python_software_st_2, kebechet_github_installations.external_software_environment_id AS kebechet_github_installations_external_software_environme_3, kebechet_github_installations.advised_python_software_stack_id AS kebechet_github_installations_advised_python_software_sta_4 
FROM kebechet_github_installations 
WHERE kebechet_github_installations.is_active IS true) AS anon_1]
(Background on this error at: http://sqlalche.me/e/13/f405)
>>> graph.get_kebechet_github_installations_count_per_is_active
<bound method GraphDatabase.get_kebechet_github_installations_count_per_is_active of GraphDatabase(_engine=Engine(postgresql+psycopg2://postgres:***@localhost:5432/postgres), _sessionmaker=sessionmaker(class_='Session', bind=Engine(postgresql+psycopg2://postgres:***@localhost:5432/postgres), autoflush=True, autocommit=False, expire_on_commit=True))>
>>> graph.get_kebechet_github_installations_count_per_is_active()
Traceback (most recent call last):
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column kebechet_github_installations.external_python_software_stack_id does not exist
LINE 2: ...st_run AS kebechet_github_installations_last_run, kebechet_g...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xtuchyna/git/forks/storages/thoth/storages/graph/postgres.py", line 3482, in get_kebechet_github_installations_count_per_is_active
    session.query(KebechetGithubAppInstallations)
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3803, in count
    return self.from_self(col).scalar()
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3523, in scalar
    ret = self.one()
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3490, in one
    ret = self.one_or_none()
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
    ret = list(self)
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/xtuchyna/.local/share/virtualenvs/storages-L98xb5vG/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column kebechet_github_installations.external_python_software_stack_id does not exist
LINE 2: ...st_run AS kebechet_github_installations_last_run, kebechet_g...
                                                             ^

[SQL: SELECT count(*) AS count_1 
FROM (SELECT kebechet_github_installations.id AS kebechet_github_installations_id, kebechet_github_installations.slug AS kebechet_github_installations_slug, kebechet_github_installations.repo_name AS kebechet_github_installations_repo_name, kebechet_github_installations.private AS kebechet_github_installations_private, kebechet_github_installations.installation_id AS kebechet_github_installations_installation_id, kebechet_github_installations.is_active AS kebechet_github_installations_is_active, kebechet_github_installations.info_manager AS kebechet_github_installations_info_manager, kebechet_github_installations.pipfile_requirements_manager AS kebechet_github_installations_pipfile_requirements_manage_1, kebechet_github_installations.update_manager AS kebechet_github_installations_update_manager, kebechet_github_installations.version_manager AS kebechet_github_installations_version_manager, kebechet_github_installations.thoth_advise_manager AS kebechet_github_installations_thoth_advise_manager, kebechet_github_installations.thoth_provenance_manager AS kebechet_github_installations_thoth_provenance_manager, kebechet_github_installations.last_run AS kebechet_github_installations_last_run, kebechet_github_installations.external_python_software_stack_id AS kebechet_github_installations_external_python_software_st_2, kebechet_github_installations.external_software_environment_id AS kebechet_github_installations_external_software_environme_3, kebechet_github_installations.advised_python_software_stack_id AS kebechet_github_installations_advised_python_software_sta_4 
FROM kebechet_github_installations 
WHERE kebechet_github_installations.is_active IS true) AS anon_1]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Comment by pacospace** [comment]
what is the alembic version you are using?

**Comment by xtuchyna** [comment]
I've taken the dump from `ocp4` and the alembic version:
`alembic==1.4.3`

**Comment by pacospace** [comment]
> I've taken the dump from `ocp4` and the alembic version i am using is:
> `alembic==1.4.3`

alembic schema version sorry :)

**Comment by xtuchyna** [comment]
according to table it is `342d45db2dc2`

**Comment by pacospace** [comment]
> 342d45db2dc2

You are using old schema: `e7ebfc165a96` is the latest version according to schema in storages. Please update schema in your postgres and you should not see those errors :)

**Comment by xtuchyna** [comment]
wip!

**Comment by xtuchyna** [comment]
yes, works like a charm. Thx!

**Comment by pacospace** [comment]
> yes, works like a charm. Thx!

Thankn you for opening issue!!
