### ISSUE TITLE
Cannot connect to the database: can't set attribute

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#2252]
**Describe the bug**

```python
2021-03-16 16:01:07,376 215742 CRITICAL root:105: Traceback (most recent call last):
  File "./thoth-adviser", line 856, in <module>
    __name__ == "__main__" and cli()
  File "/home/fpokorny/.local/share/virtualenvs/adviser-1eaKppR3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/fpokorny/.local/share/virtualenvs/adviser-1eaKppR3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/fpokorny/.local/share/virtualenvs/adviser-1eaKppR3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fpokorny/.local/share/virtualenvs/adviser-1eaKppR3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fpokorny/.local/share/virtualenvs/adviser-1eaKppR3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/fpokorny/.local/share/virtualenvs/adviser-1eaKppR3/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./thoth-adviser", line 525, in advise
    resolver = Resolver.get_adviser_instance(
  File "/home/fpokorny/git/thoth-station/adviser/thoth/adviser/resolver.py", line 1393, in get_adviser_instance
    graph.connect()
  File "/home/fpokorny/.local/share/virtualenvs/adviser-1eaKppR3/lib/python3.8/site-packages/thoth/storages/graph/postgres.py", line 299, in connect
    if not database_exists(self._engine.url):
  File "/home/fpokorny/.local/share/virtualenvs/adviser-1eaKppR3/lib/python3.8/site-packages/thoth/storages/graph/postgres_utils.py", line 82, in database_exists
    database, url.database = url.database, os.getenv('KNOWLEDGE_GRAPH_DATABASE')
AttributeError: can't set attribute
```

**To Reproduce**
1. Try to connect to the database with more recent version sqlalchemy
2. See error

**Expected behavior**

Connection should be correctly established.

**Additional context**

See change in sqlalchemy https://github.com/sqlalchemy/sqlalchemy/commit/3668b3a30c4b9a9f4af13457f43bfc34c28cf448

**Comment by harshad16** [comment]
Similar issue:https://github.com/thoth-station/metrics-exporter/issues/641

**Comment by fridex** [comment]
We will need to pin `sqlalchemy<1.4.0`.

**Comment by pacospace** [comment]
> We will need to pin `sqlalchemy<1.4.0`.

We need to wait for squalchemy-utils project, because it is not compatible with the new sqlalchemy api: https://github.com/kvesteri/sqlalchemy-utils/issues/505

**Comment by fridex** [comment]
> > We will need to pin `sqlalchemy<1.4.0`.
> 
> We need to wait for squalchemy-utils project, because it is not compatible with the new sqlalchemy api: [kvesteri/sqlalchemy-utils#505](https://github.com/kvesteri/sqlalchemy-utils/issues/505)

I think we will need to constraint `sqlalchemy<1.4.0` in the meantime until the issue in alchemy-utils is fixed. Otherwise, all the components that talk to PG will break if running newer version of sqlalchemy.

**Comment by harshad16** [comment]
Let's proceed with pinning the version, so our apps don't fail.

**Comment by pacospace** [comment]
> > > We will need to pin `sqlalchemy<1.4.0`.
> > 
> > 
> > We need to wait for squalchemy-utils project, because it is not compatible with the new sqlalchemy api: [kvesteri/sqlalchemy-utils#505](https://github.com/kvesteri/sqlalchemy-utils/issues/505)
> 
> I think we will need to constraint `sqlalchemy<1.4.0` in the meantime until the issue in alchemy-utils is fixed. Otherwise, all the components that talk to PG will break if running newer version of sqlalchemy.

Yes totally agree, sorry, my comment was just to related the issue from upstream :)

**Comment by harshad16** [comment]
This is fixed with the pinning of the sqlalchmey .
closing the issue.
Thanks everyone.
