### ISSUE TITLE
twine upload command fails uploading package to PyPI

### ISSUE THREAD

**Issue by pacospace** [thoth-station/storages#2265]
**Describe the bug**
twine command fails uploading package to PyPI

**To Reproduce**
1. Open issue to redeliver module

**Expected behavior**
new module is released on PyPI

**Screenshots**
```
+ twine upload dist/thoth_storages-0.39.3-py3-none-any.whl dist/thoth-storages-0.39.3.tar.gz
Uploading distributions to https://upload.pypi.org/legacy/
Uploading thoth_storages-0.39.3-py3-none-any.whl
  0%|          | 0.00/175k [39:17<?, ?B/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f25fbf32a90>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='upload.pypi.org', port=443): Max retries exceeded with url: /legacy/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f25fbf32a90>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/twine", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/twine/__main__.py", line 25, in main
    return dispatch(sys.argv[1:])
  File "/usr/local/lib/python3.6/site-packages/twine/cli.py", line 74, in dispatch
    return main(args.args)
  File "/usr/local/lib/python3.6/site-packages/twine/commands/upload.py", line 130, in main
    return upload(upload_settings, args.dists)
  File "/usr/local/lib/python3.6/site-packages/twine/commands/upload.py", line 82, in upload
    resp = repository.upload(package)
  File "/usr/local/lib/python3.6/site-packages/twine/repository.py", line 186, in upload
    resp = self._upload(package)
  File "/usr/local/lib/python3.6/site-packages/twine/repository.py", line 174, in _upload
    headers={'Content-Type': monitor.content_type},
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='upload.pypi.org', port=443): Max retries exceeded with url: /legacy/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f25fbf32a90>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

**Additional context**
https://github.com/thoth-station/storages/issues/2264

http://tekton-dashboard-tekton-pipelines.apps.zero.massopen.cloud/#/namespaces/opf-ci-pipelines/pipelineruns/aicoe-issue-jdhbz

**Comment by fridex** [comment]
pypi.org has partial outage

**Comment by pacospace** [comment]
> pypi.org has partial outage

Thanks @fridex ! 🍻

**Comment by goern** [comment]
sounds like we can /close this
feel free to reopen

**Comment by goern** [comment]
grmpf
/shrug
