### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'url'

### ISSUE THREAD

**Issue by harshad16** [thoth-station/storages#2355]
**Describe the bug**
this issue is cauing f34py3.9 is failing the solvers.

```
Traceback (most recent call last):
  File "app.py", line 252, in <module>
    cli()
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "app.py", line 226, in cli
    _do_sync(
  File "app.py", line 125, in _do_sync
    stats = sync_documents(
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/sync.py", line 574, in sync_documents
    stats_change = handler(
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/sync.py", line 131, in sync_solver_documents
{"name": "sentry_sdk.errors", "levelname": "DEBUG", "module": "transport", "lineno": 222, "funcname": "_send_event", "created": 1623861678.5378473, "asctime": "2021-06-16 16:41:18,537", "msecs": 537.8472805023193, "relative_created": 20702.730894088745, "process": 1, "message": "Sending event, type:null level:error event_id:e935e34978144293bf974f67909a3d3e project:1298083 host:sentry.io"}
    graph.sync_solver_result(document, force=force)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/graph/postgres.py", line 5216, in sync_solver_result
    self._refresh_rules_python_entity(session, dependency_entity)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/graph/postgres.py", line 6141, in _refresh_rules_python_entity
    for rule in self.get_python_rule_all(package_name=entity.package_name, index_url=entity.index.url, count=None):
AttributeError: 'NoneType' object has no attribute 'url'
```

**Comment by fridex** [comment]
Should be fixed in https://github.com/thoth-station/storages/pull/2337

**Comment by harshad16** [comment]
the storage is at version 0.45.1 already at graph-sync
https://github.com/thoth-station/graph-sync-job/blob/362a06a13ea92efb8e0565d9de266e006934756f/Pipfile.lock#L845

**Comment by harshad16** [comment]
the graph-sync at production is v0.10.8 , it needs to be update
