### ISSUE TITLE
event loop missing?

### ISSUE THREAD

**Issue by goern** [thoth-station/storages#255]
What if the thread has no event look? should we check if get_event_loop is None and create and assign an eventloop?

https://github.com/thoth-station/storages/blob/15a6696fbd920375aae4e62cdf89a896172b7877/thoth/storages/graph/janusgraph.py#L142

**Comment by fridex** [comment]
Is this question related to some issue?

**Comment by goern** [comment]
there might be an issue if the the connection to the graph database is opened in a thread other than the main thread. the issue might look like:

```
Traceback (most recent call last):
  File "/home/goern/.local/share/virtualenvs/metrics-exporter-ih3jJvr0/lib/python3.6/site-packages/responder/background.py", line 28, in on_future_done
    fs.result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./app.py", line 67, in update_solver_documents
    get_solver_documents()
  File "<decorator-gen-3>", line 2, in get_solver_documents
  File "/home/goern/.local/share/virtualenvs/metrics-exporter-ih3jJvr0/lib/python3.6/site-packages/prometheus_client/core.py", line 1319, in wrapped
    return func(*args, **kwargs)
  File "/home/goern/Work/thoth-station/metrics-exporter/thoth/metrics_exporter/jobs.py", line 128, in get_solver_documents
    graph_db.connect()
  File "/home/goern/.local/share/virtualenvs/metrics-exporter-ih3jJvr0/lib/python3.6/site-packages/thoth/storages/graph/janusgraph.py", line 142, in connect
    loop = asyncio.get_event_loop()
  File "/usr/lib64/python3.6/asyncio/events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/lib64/python3.6/asyncio/events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-1_0'.
```

Creating a new event loop in `ThreadPoolExecutor-1_0` and then opening a connection to graph solved problems like that.

**Comment by fridex** [comment]
JanusGraph, closing this issue.
