### ISSUE TITLE
Not compatible with Python 3.7+

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#269]
Running this library under Python 3.7+ does the following error:

```python
Traceback (most recent call last):
  File "repro.py", line 4, in <module>
    openshift = OpenShift()
  File "/home/fpokorny/.local/share/virtualenvs/a-EouiYCWm/lib/python3.7/site-packages/thoth/common/openshift.py", line 42, in __init__
    from kubernetes import client, config
  File "/home/fpokorny/.local/share/virtualenvs/a-EouiYCWm/lib/python3.7/site-packages/kubernetes/__init__.py", line 19, in <module>
    import kubernetes.client
  File "/home/fpokorny/.local/share/virtualenvs/a-EouiYCWm/lib/python3.7/site-packages/kubernetes/client/__init__.py", line 540, in <module>
    from .apis.admissionregistration_api import AdmissionregistrationApi
  File "/home/fpokorny/.local/share/virtualenvs/a-EouiYCWm/lib/python3.7/site-packages/kubernetes/client/apis/__init__.py", line 4, in <module>
    from .admissionregistration_api import AdmissionregistrationApi
  File "/home/fpokorny/.local/share/virtualenvs/a-EouiYCWm/lib/python3.7/site-packages/kubernetes/client/apis/admissionregistration_api.py", line 120
    async=params.get('async'),
        ^
SyntaxError: invalid syntax
```

**Comment by fridex** [comment]
This does not look relevant anymore. We already run on Python 3.8. Closing.
