### ISSUE TITLE
Error when syncing: Only leader can decide to commit or abort

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#671]
From cluster:

```

2019-05-06 10:19:49,793 [1] CRITICAL root:111: Traceback (most recent call last):
--
  | File "app.py", line 365, in <module>
  | cli()
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 764, in __call__
  | return self.main(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 717, in main
  | rv = self.invoke(ctx)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 956, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 555, in invoke
  | return callback(*args, **kwargs)
  | File "app.py", line 284, in cli
  | document_ids, force_sync, graceful=False
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/sync.py", line 106, in sync_solver_documents
  | graph.sync_solver_result(document)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/models_base.py", line 433, in wrapped
  | result = func(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/dgraph.py", line 1740, in sync_solver_result
  | ).get_or_create(self.client)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/models_base.py", line 409, in get_or_create
  | _, existed = self._do_upsert(client, label, label_hash, edge_def)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/models_base.py", line 148, in _do_upsert
  | transaction.commit()
  | File "/opt/app-root/lib/python3.6/site-packages/pydgraph/txn.py", line 209, in commit
  | self._common_except_commit(error)
  | File "/opt/app-root/lib/python3.6/site-packages/pydgraph/txn.py", line 230, in _common_except_commit
  | raise error
  | File "/opt/app-root/lib/python3.6/site-packages/pydgraph/txn.py", line 197, in commit
  | credentials=credentials)
  | File "/opt/app-root/lib/python3.6/site-packages/pydgraph/client_stub.py", line 62, in commit_or_abort
  | credentials=credentials)
  | File "/opt/app-root/lib/python3.6/site-packages/grpc/_channel.py", line 562, in __call__
  | return _end_unary_response_blocking(state, call, False, None)
  | File "/opt/app-root/lib/python3.6/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
  | raise _Rendezvous(state, None, None, deadline)
  | grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
  | status = StatusCode.UNKNOWN
  | details = "Only leader can decide to commit or abort"
  | debug_error_string = "{"created":"@1557137989.698827183","description":"Error received from peer ipv4:10.0.19.22:443","file":"src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"Only leader can decide to commit or abort","grpc_status":2}"

```

**Comment by fridex** [comment]
Couldn't find much information about this. In sources:

https://github.com/dgraph-io/dgraph/blob/master/dgraph/cmd/zero/oracle.go#L416

**Comment by fridex** [comment]
Closing, a duplicate of https://github.com/thoth-station/storages/issues/686
