### ISSUE TITLE
Error in get_all_versions_python_package query

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#727]
```

---> Running application from script (app.sh) ...
--
  | 2019-06-03 06:49:12,442 [1] INFO     root:117: Setting up logging to a Sentry instance 'sentry.io/1298083'
  | 2019-06-03 06:49:12,448 [1] INFO     root:148: Logging to rsyslog endpoint is turned off
  | 2019-06-03 06:49:12,450 [1] INFO     __main__:131: Version: 0.4.0
  | 2019-06-03 06:49:12,520 [1] INFO     __main__:379: Runtime environment configuration:
  | {
  | "cuda_version": null,
  | "hardware": {
  | "cpu_family": null,
  | "cpu_model": null
  | },
  | "name": "fedora:28",
  | "operating_system": {
  | "name": "fedora:28",
  | "version": "28"
  | },
  | "python_version": "3.6"
  | }
  | 2019-06-03 06:49:12,520 [1] INFO     __main__:389: No library usage supplied
  | 2019-06-03 06:49:12,522 [1] INFO     thoth.adviser.python.pipeline.pipeline:94: Resolving direct dependencies
  | 2019-06-03 06:49:12,523 [1] INFO     thoth.solver.python.python_solver:113: Parsing dependency 'flask'
  | 2019-06-03 06:49:22,608 [1] CRITICAL root:111: Traceback (most recent call last):
  | File "thoth-adviser", line 701, in <module>
  | cli()
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 716, in __call__
  | return self.main(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 696, in main
  | rv = self.invoke(ctx)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1060, in invoke
  | return _process_result(sub_ctx.command.invoke(sub_ctx))
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 889, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 534, in invoke
  | return callback(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
  | return f(get_current_context(), *args, **kwargs)
  | File "thoth-adviser", line 396, in advise
  | limit_latest_versions=limit_latest_versions,
  | File "/opt/app-root/src/thoth/adviser/python/advise.py", line 116, in compute_on_project
  | library_usage=library_usage,
  | File "/opt/app-root/src/thoth/adviser/python/advise.py", line 73, in compute
  | for product in pipeline.conduct(count=self.count, limit=self.limit):
  | File "/opt/app-root/src/thoth/adviser/python/pipeline/pipeline.py", line 205, in conduct
  | step_context = self._initialize_stepping()
  | File "/opt/app-root/src/thoth/adviser/python/pipeline/pipeline.py", line 152, in _initialize_stepping
  | step_context = self._prepare_direct_dependencies(with_devel=True)
  | File "/opt/app-root/src/thoth/adviser/python/pipeline/pipeline.py", line 99, in _prepare_direct_dependencies
  | all_versions=True,
  | File "/opt/app-root/src/thoth/adviser/python/solver.py", line 145, in solve
  | dependencies, graceful=graceful, all_versions=all_versions
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/solver/python/base.py", line 268, in solve
  | name, releases = self.release_fetcher.fetch_releases(dep.name)
  | File "/opt/app-root/src/thoth/adviser/python/solver.py", line 71, in fetch_releases
  | without_error=True,
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/dgraph.py", line 650, in get_all_versions_python_package
  | result = self._query_raw(query)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/dgraph.py", line 247, in _query_raw
  | result = txn.query(query, variables=variables)
  | File "/opt/app-root/lib/python3.6/site-packages/pydgraph/txn.py", line 82, in query
  | raise error
  | File "/opt/app-root/lib/python3.6/site-packages/pydgraph/txn.py", line 73, in query
  | credentials=credentials)
  | File "/opt/app-root/lib/python3.6/site-packages/pydgraph/client_stub.py", line 51, in query
  | credentials=credentials)
  | File "/opt/app-root/lib/python3.6/site-packages/grpc/_channel.py", line 562, in __call__
  | return _end_unary_response_blocking(state, call, False, None)
  | File "/opt/app-root/lib/python3.6/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
  | raise _Rendezvous(state, None, None, deadline)
  | grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
  | status = StatusCode.UNKNOWN
  | details = "Expected arg after func [eq], but got item lex.Item [14] ":""
  | debug_error_string = "{"created":"@1559544562.545867222","description":"Error received from peer ipv4:10.0.19.23:443","file":"src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"Expected arg after func [eq], but got item lex.Item [14] ":"","grpc_status":2}"
```

**Comment by fridex** [comment]
Runtime environment configuration was:


```json
{"operating_system": {"name": "fedora:28", "version": "28"}, "python_version": "3.6", "name": "fedora:28"}
```
